"use client";
import { useEffect, useMemo, useState } from "react";

type Place={slug:string;name:string;region:string;summary:string;best_time:string};
type Item={time:string;title:string;kind:string;note?:string};
type Day={day:number;destination:Place;focus:string;transfer?:{from:string;km:number;minutes:number};items:Item[]};
type Result={aiPowered:boolean;profile:{days:number;travelers:number;interests:string[];budget:string;pace:string;startingPoint:string;prompt:string};route:Place[];itinerary:Day[];experiences:{slug:string;name:string;summary:string|null;destination_name:string|null}[];narrative:string;estimatedDailyRate:number;tripId?:string|null;synced:boolean};

const interests=["Mountains","Coast","Wildlife","Culture","Food","Slow travel"];
const examples=["6 days, mountains + food, relaxed", "A premium 7 day first trip with wildlife", "3 days around Kandy and Sigiriya"];
export default function ConciergePage(){
 const [prompt,setPrompt]=useState(""); const [days,setDays]=useState(7); const [travelers,setTravelers]=useState(2); const [chosen,setChosen]=useState<string[]>(["Mountains","Food"]); const [budget,setBudget]=useState("Comfort"); const [pace,setPace]=useState("Balanced"); const [start,setStart]=useState("Flexible"); const [result,setResult]=useState<Result|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{const saved=localStorage.getItem("discoverlanka-concierge");if(saved)try{setResult(JSON.parse(saved));}catch{}},[]);
 const profileLine=useMemo(()=>`${days} days · ${travelers} traveller${travelers===1?"":"s"} · ${budget}`,[days,travelers,budget]);
 function toggle(v:string){setChosen(x=>x.includes(v)?x.filter(i=>i!==v):[...x,v].slice(0,4));}
 async function reveal(){setLoading(true);setError("");try{const r=await fetch("/api/concierge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({days,travelers,interests:chosen,budget,pace,startingPoint:start,prompt})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not build journey");setResult(d);localStorage.setItem("discoverlanka-concierge",JSON.stringify(d));if(d.tripId)localStorage.setItem("discoverlanka-trip-id",d.tripId);if(d.routeSlugs)localStorage.setItem("discoverlanka-saved",JSON.stringify(d.routeSlugs));}catch(e){setError(e instanceof Error?e.message:"Could not build journey")}finally{setLoading(false)}}
 return <main className="min-h-screen px-5 pb-24 pt-24 text-[#f4efe6] sm:px-8 md:pt-28"><div className="mx-auto max-w-7xl">
  <header className="mb-8 flex items-center justify-between"><a href="/" className="text-xl font-semibold">Discover<span className="text-[#d8b875]">Lanka</span></a><div className="flex gap-3"><a href="/account" className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-bold">Account</a><a href="/my-trip" className="rounded-full bg-[#d8b875] px-4 py-2 text-xs font-bold text-[#09140f]">My Trip ↗</a></div></header>
  <section className="route-hero-panel overflow-hidden p-6 sm:p-10 md:p-14"><div className="max-w-4xl"><p className="luxury-section-eyebrow">AI travel concierge</p><h1 className="luxury-display-small mt-4 text-5xl md:text-8xl">Tell us how you want Sri Lanka to feel.</h1><p className="mt-5 max-w-2xl text-base leading-8 text-white/62 md:text-lg">Write naturally or shape the profile below. DiscoverLanka will turn the brief into a route, a day-by-day rhythm and moments worth keeping.</p></div>
   <div className="mt-10 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="luxury-glass rounded-[26px] p-5 sm:p-7"><label className="text-xs font-bold uppercase tracking-[.17em] text-[#d8b875]">Your travel brief</label><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="e.g. 6 days, mountains + food, relaxed pace, premium feel…" className="mt-3 min-h-32 w-full resize-none rounded-2xl border border-white/10 bg-black/15 p-4 text-base text-white outline-none placeholder:text-white/28"/ ><div className="mt-3 flex flex-wrap gap-2">{examples.map(x=><button key={x} onClick={()=>setPrompt(x)} className="rounded-full border border-white/10 bg-white/[.03] px-3 py-2 text-xs text-white/52 hover:border-[#d8b875]/30 hover:text-white">{x}</button>)}</div><button onClick={reveal} disabled={loading} className="mt-5 w-full rounded-full bg-[#d8b875] px-6 py-4 text-sm font-extrabold text-[#09140f]">{loading?"Shaping your journey…":"Reveal my journey ↗"}</button></div>
    <div className="luxury-glass rounded-[26px] p-5 sm:p-7"><div className="flex items-center justify-between"><p className="luxury-section-eyebrow">Quick profile</p><span className="text-xs text-white/35">{profileLine}</span></div><div className="mt-5"><p className="text-xs uppercase tracking-[.16em] text-white/40">Interests</p><div className="mt-3 flex flex-wrap gap-2">{interests.map(x=><button key={x} onClick={()=>toggle(x)} className={`rounded-full border px-3 py-2 text-xs font-semibold ${chosen.includes(x)?"border-[#d8b875]/50 bg-[#d8b875]/12 text-[#f4efe6]":"border-white/10 bg-white/[.03] text-white/48"}`}>{x}</button>)}</div></div><div className="mt-6 grid grid-cols-2 gap-3"><div><p className="text-xs uppercase tracking-[.16em] text-white/40">Days</p><div className="mt-2 flex items-center gap-3"><button onClick={()=>setDays(Math.max(2,days-1))} className="h-9 w-9 rounded-full border border-white/10">−</button><strong>{days}</strong><button onClick={()=>setDays(Math.min(21,days+1))} className="h-9 w-9 rounded-full border border-white/10">+</button></div></div><div><p className="text-xs uppercase tracking-[.16em] text-white/40">Travellers</p><div className="mt-2 flex items-center gap-3"><button onClick={()=>setTravelers(Math.max(1,travelers-1))} className="h-9 w-9 rounded-full border border-white/10">−</button><strong>{travelers}</strong><button onClick={()=>setTravelers(Math.min(10,travelers+1))} className="h-9 w-9 rounded-full border border-white/10">+</button></div></div></div><div className="mt-6"><p className="text-xs uppercase tracking-[.16em] text-white/40">Pace</p><div className="mt-2 flex gap-2">{["Slow","Balanced","Fast"].map(x=><button key={x} onClick={()=>setPace(x)} className={`flex-1 rounded-xl border px-3 py-2 text-xs ${pace===x?"border-[#d8b875]/50 bg-[#d8b875]/12":"border-white/10 bg-white/[.03] text-white/45"}`}>{x}</button>)}</div></div><div className="mt-5"><p className="text-xs uppercase tracking-[.16em] text-white/40">Travel style</p><div className="mt-2 flex gap-2">{["Budget","Comfort","Premium"].map(x=><button key={x} onClick={()=>setBudget(x)} className={`flex-1 rounded-xl border px-3 py-2 text-xs ${budget===x?"border-[#d8b875]/50 bg-[#d8b875]/12":"border-white/10 bg-white/[.03] text-white/45"}`}>{x}</button>)}</div></div></div></div>
  </section>
  {error&&<div className="mt-5 rounded-2xl border border-red-300/20 bg-red-400/10 p-4 text-sm text-red-100">{error}</div>}
  {result&&<section className="mt-7 space-y-6"><div className="route-hero-panel p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="luxury-section-eyebrow">{result.aiPowered?"AI-crafted journey":"Smart-crafted journey"}</p><h2 className="mt-2 font-serif text-4xl md:text-5xl">{result.route.map(x=>x.name).join(" → ")}</h2><p className="mt-3 max-w-3xl text-white/62">{result.narrative}</p></div><div className="rounded-full border border-[#d8b875]/25 bg-[#d8b875]/8 px-4 py-2 text-xs font-bold text-[#d8b875]">{result.profile.days} days</div></div><div className="mt-7 flex flex-wrap gap-2">{result.profile.interests.map(x=><span key={x} className="rounded-full border border-white/10 bg-white/[.03] px-3 py-2 text-xs text-white/55">{x}</span>)}<span className="rounded-full border border-white/10 bg-white/[.03] px-3 py-2 text-xs text-white/55">{result.profile.pace} pace</span><span className="rounded-full border border-white/10 bg-white/[.03] px-3 py-2 text-xs text-white/55">{result.profile.budget}</span>{result.synced&&<span className="rounded-full border border-emerald-300/20 bg-emerald-400/8 px-3 py-2 text-xs text-emerald-100">Saved to account</span>}</div></div>
   <div className="luxury-glass rounded-[26px] p-6 sm:p-8"><div className="flex items-end justify-between gap-4"><div><p className="luxury-section-eyebrow">Day by day</p><h2 className="mt-2 font-serif text-4xl">A realistic rhythm.</h2></div><a href="/my-trip" className="text-xs font-bold uppercase tracking-[.16em] text-white/45">Open dossier ↗</a></div><div className="mt-7 grid gap-4 lg:grid-cols-2">{result.itinerary.map(day=><article key={day.day} className="rounded-[22px] border border-white/8 bg-black/12 p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.17em] text-[#d8b875]">Day {day.day} · {day.focus}</p><h3 className="mt-1 font-serif text-2xl">{day.destination.name}</h3><p className="text-xs text-white/42">{day.destination.region}</p></div>{day.transfer&&<span className="rounded-full border border-white/8 bg-white/[.03] px-3 py-1 text-[10px] text-white/42">{day.transfer.from} → {day.destination.name} · ~{day.transfer.minutes}m</span>}</div><div className="mt-5 space-y-2">{day.items.map((item,i)=><div key={i} className="rounded-xl border border-white/7 bg-white/[.025] p-3"><div className="flex gap-3"><span className="w-14 shrink-0 text-[10px] font-bold uppercase tracking-[.12em] text-[#d8b875]">{item.time}</span><div><p className="text-sm font-semibold text-white/86">{item.title}</p>{item.note&&<p className="mt-1 text-xs leading-5 text-white/42">{item.note}</p>}</div></div></div>)}</div></article>)}</div></div>
   <div className="flex flex-wrap gap-3"><button onClick={()=>{setResult(null);setPrompt("");}} className="rounded-full border border-white/10 bg-white/[.03] px-5 py-3 text-sm font-semibold">Start again</button>{result.tripId&&<a href="/my-trip" className="rounded-full bg-[#d8b875] px-6 py-3 text-sm font-bold text-[#09140f]">Keep this journey ↗</a>}</div>
  </section>}
 </div></main>
}
