import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { neon } from "@neondatabase/serverless";

export const dynamic="force-dynamic";
type Story={id:string;slug:string;title:string;excerpt:string;content:string;category:string;published_at:string|null};
const heroImages=["https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=2200&q=88","https://images.unsplash.com/photo-1518002054494-3a6f94352e9d?auto=format&fit=crop&w=2200&q=88","https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=2200&q=88"];
async function getStory(slug:string){if(!process.env.DATABASE_URL)return null;const sql=neon(process.env.DATABASE_URL);const rows=await sql`SELECT id,slug,title,excerpt,content,category,published_at FROM articles WHERE slug=${slug} LIMIT 1`;return (rows[0] as Story|undefined)??null}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const s=await getStory(slug).catch(()=>null);if(!s)return {title:"Story not found | DiscoverLanka"};return {title:`${s.title} | DiscoverLanka`,description:s.excerpt||`Read ${s.title} on DiscoverLanka.`,alternates:{canonical:`/stories/${s.slug}`},openGraph:{title:`${s.title} | DiscoverLanka`,description:s.excerpt||"",type:"article",images:[{url:heroImages[0],alt:s.title}]}}}
export default async function StoryPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=await getStory(slug).catch(()=>null);if(!s)notFound();const image=heroImages[Math.abs(s.slug.length)%heroImages.length];return <main className="min-h-screen bg-[#07120f] text-[#f4efe6]">
<header className="sticky top-0 z-40 px-3 pt-3 sm:px-5"><div className="mx-auto flex max-w-7xl items-center justify-between rounded-full border border-white/10 bg-black/20 px-5 py-4 backdrop-blur-xl"><a href="/" className="text-xl font-semibold">Discover<span className="text-[#d8b875]">Lanka</span></a><div className="flex items-center gap-4"><a href="/stories" className="text-sm font-semibold text-white/65">Journal</a><a href="/plan" className="premium-button premium-button-gold rounded-full px-4 py-2 text-xs font-extrabold">Build My Trip ↗</a></div></div></header>
<section className="mx-auto max-w-7xl px-5 pb-16 pt-20 sm:px-8 md:pt-28"><div className="relative min-h-[590px] overflow-hidden rounded-[2.2rem] border border-white/10"><img src={image} alt={s.title} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#06100d] via-[#06100d]/20 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7 sm:p-10"><div className="route-hero-panel max-w-4xl"><p className="luxury-section-eyebrow">{s.category||"Sri Lanka"} · JOURNAL</p><h1 className="luxury-display-small mt-3 text-5xl md:text-7xl">{s.title}</h1>{s.excerpt&&<p className="mt-5 max-w-3xl text-lg leading-8 text-white/68">{s.excerpt}</p>}</div></div></div></section>
<section className="mx-auto max-w-3xl px-5 pb-24 sm:px-8"><div className="prose prose-invert max-w-none prose-p:text-white/70 prose-p:leading-8" dangerouslySetInnerHTML={{__html:s.content}}/></section>
</main>}
