import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { neon } from "@neondatabase/serverless";
import ReviewSection from "@/components/ReviewSection";

export const dynamic="force-dynamic";

type Destination={id:string;slug:string;name:string;region:string;summary:string;description:string;latitude:number;longitude:number;best_time:string};
type Experience={id:string;slug:string;name:string;category:string|null;summary:string|null;price_from:number|null;currency:string};
const images:Record<string,string>={
 kandy:"https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=2200&q=88",
 ella:"https://images.unsplash.com/photo-1586613837427-44f7a0b1e5e6?auto=format&fit=crop&w=2200&q=88",
 galle:"https://images.unsplash.com/photo-1566296314736-6eaac1ca0cb9?auto=format&fit=crop&w=2200&q=88",
 sigiriya:"https://images.unsplash.com/photo-1588598198321-9735fd5246b8?auto=format&fit=crop&w=2200&q=88",
 yala:"https://images.unsplash.com/photo-1557008075-7f2c5efa4cfd?auto=format&fit=crop&w=2200&q=88",
 mirissa:"https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?auto=format&fit=crop&w=2200&q=88",
 "nuwara-eliya":"https://images.unsplash.com/photo-1590123221594-8c5d2c5f3f44?auto=format&fit=crop&w=2200&q=88",
 anuradhapura:"https://images.unsplash.com/photo-1588258524675-c7f1e3e8d5d8?auto=format&fit=crop&w=2200&q=88",
 trincomalee:"https://images.unsplash.com/photo-1694869248690-2956574b7032?auto=format&fit=crop&w=2200&q=88",
 "arugam-bay":"https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?auto=format&fit=crop&w=2200&q=88",
 jaffna:"https://images.unsplash.com/photo-1725773682183-f0c885081ce5?auto=format&fit=crop&w=2200&q=88",
 udawalawe:"https://images.unsplash.com/photo-1557008075-7f2c5efa4cfd?auto=format&fit=crop&w=2200&q=88"
};
const guide:Record<string,{mood:string;highlights:string[];tips:string[]}>= {
 kandy:{mood:"Culture, ceremony & cool hill-country evenings",highlights:["Walk the lake and old city at an unhurried pace","Make time for local food and tea","Pair the city with a quieter hill-country stop"],tips:["Start cultural visits earlier in the day","Leave space for traffic and hill roads","Use this as a base for short Central Province day trips"]},
 ella:{mood:"Mountain views, walks & slow mornings",highlights:["Build days around one main trail or viewpoint","Keep time for tea-country landscapes","Mix popular sights with quieter village roads"],tips:["Weather can change quickly in the hills","Do not over-pack the day with viewpoints","Early starts usually make the day feel calmer"]},
 galle:{mood:"Heritage walls, cafés & the southern coast",highlights:["Explore the historic fort on foot","Add a beach or coastal stop nearby","Use the evening for a slower old-town wander"],tips:["Comfortable shoes help on long fort walks","Sunset is a good time for a relaxed coastal plan","Combine with nearby south-coast beaches for longer stays"]},
 sigiriya:{mood:"Ancient landscapes, rock views & dry-zone adventure",highlights:["Go early for a cooler climb","Pair the rock area with another heritage stop","Use the surrounding countryside for a slower afternoon"],tips:["Protect the morning for your main climb","Carry water and plan a recovery break","Avoid making every stop a major attraction"]},
 yala:{mood:"Wildlife, open landscapes & nature-first days",highlights:["Keep safari time as the anchor of the day","Leave room for the surrounding landscape","Choose slower evenings after an early start"],tips:["Treat wildlife viewing as an unhurried experience","Keep expectations flexible around animal sightings","Pair wildlife days with recovery time rather than back-to-back activities"]},
 mirissa:{mood:"Beach mornings, sea air & relaxed coastal nights",highlights:["Start with a quiet shoreline walk","Leave afternoons flexible around the heat","Finish with a sunset and local dinner"],tips:["Keep marine activities tied to current local conditions","Build in a slower afternoon","Combine with nearby south-coast towns for variety"]},
 "nuwara-eliya":{mood:"Tea country, misty hills & cool-weather escapes",highlights:["Spend time among tea landscapes","Choose one scenic road or viewpoint","Keep evenings simple and warm"],tips:["Pack for cooler evenings","Allow more time for winding hill roads","Do not judge the day only by visibility; mist is part of the mood"]},
 anuradhapura:{mood:"Ancient city, sacred spaces & wide-open history",highlights:["Give major heritage areas plenty of time","Move between sites at a calm pace","Pair history with nearby cultural stops"],tips:["Dress respectfully at sacred sites","Plan around heat and walking time","An early start makes a long heritage day more comfortable"]},
 trincomalee:{mood:"Turquoise water, sacred cliffs & slow east-coast days",highlights:["Give Nilaveli or Uppuveli a full unhurried morning","Pair the coast with Fort Frederick and Koneswaram","Leave an evening free for the harbour sunset"],tips:["May to September is the strongest east-coast window","Keep marine plans flexible around sea conditions","Allow extra time for the northbound coastal road"]},
 "arugam-bay":{mood:"Surf, lagoons & easygoing east-coast village life",highlights:["Build the day around the surf conditions","Explore lagoon and wildlife areas away from the main strip","Keep evenings relaxed with local food and a beach walk"],tips:["May to September is the main surf season","Use a local instructor if you are new to the breaks","Do not pack surf, lagoon and safari activities into one rushed day"]},
 jaffna:{mood:"Northern heritage, bold flavours & island-road discovery",highlights:["Spend time around Nallur and the old city","Explore the food culture through a local-led trail","Keep a half-day for a quieter island or coastal drive"],tips:["Dress respectfully at active religious sites","Midday heat can be strong, so pace long walks","Leave room for local food stops rather than fixed meal times"]},
 udawalawe:{mood:"Open grasslands, elephants & quiet wildlife mornings",highlights:["Make an early safari the anchor of the stay","Use the afternoon for a slower village or countryside experience","Keep the route flexible around wildlife and heat"],tips:["Early starts are usually the most comfortable","Wildlife sightings are never guaranteed, so keep expectations flexible","Combine safari time with a rest period rather than another long drive"]}
};
async function getDestination(slug:string){if(!process.env.DATABASE_URL)return null;const sql=neon(process.env.DATABASE_URL);const rows=await sql`SELECT id,slug,name,region,summary,description,latitude,longitude,best_time FROM destinations WHERE slug=${slug} LIMIT 1`;return (rows[0] as Destination|undefined)??null}
async function getExperiences(id:string){if(!process.env.DATABASE_URL)return [];const sql=neon(process.env.DATABASE_URL);const rows=await sql`SELECT id,slug,name,category,summary,price_from,currency FROM experiences WHERE destination_id=${id} ORDER BY created_at DESC LIMIT 4`;return rows as Experience[]}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const d=await getDestination(slug).catch(()=>null);if(!d)return {title:"Destination not found | DiscoverLanka"};return {title:`${d.name}, Sri Lanka | DiscoverLanka`,description:d.summary,alternates:{canonical:`/destinations/${d.slug}`},openGraph:{title:`${d.name}, Sri Lanka | DiscoverLanka`,description:d.summary,type:"article",images:[{url:images[d.slug]??images.ella,alt:d.name}]}}}
export default async function DestinationPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const d=await getDestination(slug).catch(()=>null);if(!d)notFound();const image=images[d.slug]??images.ella;const g=guide[d.slug]??{mood:"A Sri Lankan place worth exploring at your own pace",highlights:["Take the day slowly and leave room for discovery","Mix a signature sight with a quieter local experience","Use the destination as one part of a wider route"],tips:["Check your route before locking in every stop","Leave buffer time for transport","Build the day around your interests"]};const experiences=await getExperiences(d.id);return <main className="min-h-screen bg-[#07120f] text-[#f4efe6]">
<header className="absolute inset-x-0 top-0 z-30 px-4 pt-4 sm:px-6"><div className="mx-auto flex max-w-7xl items-center justify-between rounded-full border border-white/12 bg-black/20 px-5 py-4 backdrop-blur-xl"><a href="/" className="text-xl font-semibold">Discover<span className="text-[#d8b875]">Lanka</span></a><a href="/destinations" className="rounded-full border border-white/15 bg-white/5 px-4 py-2 text-xs font-bold uppercase tracking-[.14em] text-white/70">← Destinations</a></div></header>
<section className="relative min-h-[78svh] overflow-hidden"><img src={image} alt={d.name} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(3,10,8,.30),rgba(3,10,8,.15)_35%,rgba(3,10,8,.96)_100%)]"/><div className="relative mx-auto flex min-h-[78svh] max-w-7xl items-end px-5 pb-12 pt-40 sm:px-8 md:pb-16"><div className="route-hero-panel max-w-3xl"><p className="luxury-section-eyebrow">{d.region}</p><h1 className="luxury-display-small mt-3 text-6xl md:text-8xl">{d.name}</h1><p className="mt-5 max-w-2xl text-base leading-8 text-white/70 md:text-lg">{d.summary}</p><div className="mt-7 flex flex-wrap gap-3"><a href={`/plan?destination=${encodeURIComponent(d.slug)}`} className="premium-button premium-button-gold rounded-full px-6 py-3 text-xs font-extrabold uppercase tracking-[.16em]">Build My Trip ↗</a><a href="#experiences" className="rounded-full border border-white/15 bg-white/5 px-5 py-3 text-xs font-bold uppercase tracking-[.16em] text-white/70">Explore experiences</a></div></div></div></section>
<section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[1fr_340px]"><article><p className="luxury-section-eyebrow">About the destination</p><h2 className="mt-3 luxury-display-small text-5xl md:text-6xl">A place worth taking your time with.</h2><p className="mt-7 whitespace-pre-line text-base leading-8 text-white/65 md:text-lg">{d.description}</p><div className="mt-12 grid gap-5 md:grid-cols-2"><div className="luxury-glass rounded-[1.8rem] p-7"><p className="luxury-section-eyebrow">The feel</p><h3 className="mt-3 font-serif text-2xl leading-tight">{g.mood}</h3></div><div className="luxury-glass rounded-[1.8rem] p-7"><p className="luxury-section-eyebrow">Best time</p><h3 className="mt-3 font-serif text-2xl">{d.best_time}</h3></div></div></article><aside className="route-hero-panel h-fit"><p className="luxury-section-eyebrow">Plan your visit</p><div className="mt-6 space-y-5"><div><span className="text-[10px] uppercase tracking-[.18em] text-white/45">Region</span><strong className="mt-1 block">{d.region}</strong></div><div><span className="text-[10px] uppercase tracking-[.18em] text-white/45">Coordinates</span><strong className="mt-1 block">{d.latitude.toFixed(4)}, {d.longitude.toFixed(4)}</strong></div></div><a href={`/plan?destination=${encodeURIComponent(d.slug)}`} className="premium-button premium-button-gold mt-8 block rounded-full px-5 py-3 text-center text-xs font-extrabold uppercase tracking-[.16em]">Plan around {d.name} ↗</a></aside></section>
<section className="mx-auto max-w-7xl px-5 pb-20 sm:px-8"><div className="grid gap-8 md:grid-cols-2"><div className="luxury-glass rounded-[2rem] p-7 sm:p-9"><p className="luxury-section-eyebrow">Good reasons to go</p><div className="mt-5 space-y-3">{g.highlights.map((x)=><div key={x} className="rounded-2xl border border-white/8 bg-white/[.035] p-4 text-sm leading-6 text-white/65">{x}</div>)}</div></div><div className="luxury-glass rounded-[2rem] p-7 sm:p-9"><p className="luxury-section-eyebrow">Planning notes</p><div className="mt-5 space-y-3">{g.tips.map((x)=><div key={x} className="rounded-2xl border border-white/8 bg-white/[.035] p-4 text-sm leading-6 text-white/65">{x}</div>)}</div></div></div></section>
{experiences.length>0&&<section id="experiences" className="mx-auto max-w-7xl px-5 pb-20 sm:px-8"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="luxury-section-eyebrow">Nearby experiences</p><h2 className="mt-3 luxury-display-small text-5xl">Make the place feel local.</h2></div><a href="/experiences" className="text-xs font-bold uppercase tracking-[.17em] text-white/55 hover:text-white">See all ↗</a></div><div className="mt-8 grid gap-5 md:grid-cols-2">{experiences.map((x,i)=><a key={x.id} href={`/experiences/${x.slug}`} className="luxury-glass group overflow-hidden rounded-[2rem]"><div className="relative h-56 overflow-hidden"><img src={(images[d.slug]??images.ella)} alt="" className="h-full w-full object-cover opacity-80 transition duration-1000 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-[#07120f] to-transparent"/><span className="absolute left-5 top-5 rounded-full border border-white/15 bg-black/25 px-3 py-1 text-[10px] font-bold uppercase tracking-[.18em]">0{i+1} · {x.category??"Experience"}</span></div><div className="p-6"><h3 className="font-serif text-3xl">{x.name}</h3><p className="mt-3 text-sm leading-6 text-white/58">{x.summary}</p>{x.price_from!=null&&<p className="mt-4 text-xs font-semibold text-[#d8b875]">From {x.currency} {Number(x.price_from).toLocaleString("en-LK")}</p>}</div></a>)}</div></section>}
<div className="mx-auto max-w-7xl px-5 pb-24 sm:px-8"><ReviewSection destinationId={d.id} destinationName={d.name}/></div>
</main>}
