import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { neon } from "@neondatabase/serverless";
import ReviewSection from "@/components/ReviewSection";

export const dynamic="force-dynamic";

type Destination={id:string;slug:string;name:string;region:string;summary:string;description:string;latitude:number;longitude:number;best_time:string};
const images:Record<string,string>={
 kandy:"https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=2200&q=88",
 ella:"https://images.unsplash.com/photo-1586613837427-44f7a0b1e5e6?auto=format&fit=crop&w=2200&q=88",
 galle:"https://images.unsplash.com/photo-1566296314736-6eaac1ca0cb9?auto=format&fit=crop&w=2200&q=88",
 sigiriya:"https://images.unsplash.com/photo-1588598198321-9735fd5246b8?auto=format&fit=crop&w=2200&q=88",
 yala:"https://images.unsplash.com/photo-1557008075-7f2c5efa4cfd?auto=format&fit=crop&w=2200&q=88",
 mirissa:"https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?auto=format&fit=crop&w=2200&q=88",
 "nuwara-eliya":"https://images.unsplash.com/photo-1590123221594-8c5d2c5f3f44?auto=format&fit=crop&w=2200&q=88",
 anuradhapura:"https://images.unsplash.com/photo-1588258524675-c7f1e3e8d5d8?auto=format&fit=crop&w=2200&q=88",
 trincomalee:"https://images.unsplash.com/photo-1694869248690-2956574b7032?auto=format&fit=crop&w=2200&q=88",
 "arugam-bay":"https://yalu.travel/content/images/2025/08/yalulife_arugam_bay_surfing.jpg",
 jaffna:"https://images.unsplash.com/photo-1725773682183-f0c885081ce5?auto=format&fit=crop&w=2200&q=88",
 udawalawe:"https://advantiko.com/wp-content/uploads/2020/06/udawalawe-national-park2.jpg",
 "adams-peak":"https://commons.wikimedia.org/wiki/Special:FilePath/Sri%20Padaya%20-%20Adam%27s%20peak.jpg"
};
const galleries:Record<string,{src:string;alt:string;caption:string}[]>={
 "adams-peak":[
  {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Sri%20Padaya%20-%20Adam%27s%20peak.jpg",alt:"Sri Pada at sunrise",caption:"Sri Pada in the early morning light"},
  {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Along%20the%20way%20to%20Sri%20Pada.JPG",alt:"Path to Sri Pada",caption:"The pilgrimage path towards the summit"},
  {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Sripada-crowd.jpg",alt:"Pilgrims at Sri Pada",caption:"Pilgrims on the mountain during the season"},
  {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Sunrise%20view%20from%20the%20top%20of%20Adam%27s%20Peak.jpg",alt:"Sunrise view from Adam's Peak",caption:"The sunrise view from the summit"},
  {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Sripada%20night%20sky.jpg",alt:"Sri Pada night sky",caption:"The mountain before dawn"},
  {src:"https://commons.wikimedia.org/wiki/Special:FilePath/Sri%20Pada%20Mountain%20(Adams%20Peak).jpg",alt:"Sri Pada mountain landscape",caption:"Sri Pada rising above the surrounding hills"}
 ]};
const aboutDescriptions:Record<string,string>= {
 "adams-peak":`Adam’s Peak, known locally as Sri Pada and Samanala Kanda, is a 2,243-metre sacred mountain in the central highlands of Sri Lanka. Its distinctive summit has been revered for centuries because of the sacred footprint-shaped rock formation at the top. Different religious traditions attach different meanings to the footprint, making Sri Pada an important pilgrimage site shared across communities.

During the main pilgrimage season, generally from December to May, devotees and travellers climb the mountain through the night to reach the summit around sunrise. The journey is more than a physical climb: the route passes through forested mountain scenery, rest points, shrines and places connected with long-standing pilgrimage customs. Near the summit, the staircase becomes steeper and the weather can be colder and changeable.

When the sky is clear, sunrise from the summit reveals the surrounding highlands and can create the mountain’s famous triangular shadow. The wider Peak Wilderness landscape adds another dimension to the visit, with steep forested slopes, streams and important highland ecosystems.

For a first-time visitor, Sri Pada is best understood as a combination of sacred heritage, mountain scenery and a demanding walking journey. Respect for pilgrims and religious customs is an important part of experiencing the destination responsibly.`,
};
const guide:Record<string,{mood:string;highlights:string[];tips:string[]}>= {
 kandy:{mood:"Culture, ceremony & cool hill-country evenings",highlights:["Walk the lake and old city at an unhurried pace","Make time for local food and tea","Pair the city with a quieter hill-country stop"],tips:["Start cultural visits earlier in the day","Leave space for traffic and hill roads","Use this as a base for short Central Province day trips"]},
 ella:{mood:"Mountain views, walks & slow mornings",highlights:["Build days around one main trail or viewpoint","Keep time for tea-country landscapes","Mix popular sights with quieter village roads"],tips:["Weather can change quickly in the hills","Do not over-pack the day with viewpoints","Early starts usually make the day feel calmer"]},
 galle:{mood:"Heritage walls, cafés & the southern coast",highlights:["Explore the historic fort on foot","Add a beach or coastal stop nearby","Use the evening for a slower old-town wander"],tips:["Comfortable shoes help on long fort walks","Sunset is a good time for a relaxed coastal plan","Combine with nearby south-coast beaches for longer stays"]},
 sigiriya:{mood:"Ancient landscapes, rock views & dry-zone adventure",highlights:["Go early for a cooler climb","Pair the rock area with another heritage stop","Use the surrounding countryside for a slower afternoon"],tips:["Protect the morning for your main climb","Carry water and plan a recovery break","Avoid making every stop a major attraction"]},
 yala:{mood:"Wildlife, open landscapes & nature-first days",highlights:["Keep safari time as the anchor of the day","Leave room for the surrounding landscape","Choose slower evenings after an early start"],tips:["Treat wildlife viewing as an unhurried experience","Keep expectations flexible around animal sightings","Pair wildlife days with recovery time rather than back-to-back activities"]},
 mirissa:{mood:"Beach mornings, sea air & relaxed coastal nights",highlights:["Start with a quiet shoreline walk","Leave afternoons flexible around the heat","Finish with a sunset and local dinner"],tips:["Keep marine activities tied to current local conditions","Build in a slower afternoon","Combine with nearby south-coast towns for variety"]},
 "nuwara-eliya":{mood:"Tea country, misty hills & cool-weather escapes",highlights:["Spend time among tea landscapes","Choose one scenic road or viewpoint","Keep evenings simple and warm"],tips:["Pack for cooler evenings","Allow more time for winding hill roads","Do not judge the day only by visibility; mist is part of the mood"]},
 anuradhapura:{mood:"Ancient city, sacred spaces & wide-open history",highlights:["Give major heritage areas plenty of time","Move between sites at a calm pace","Pair history with nearby cultural stops"],tips:["Dress respectfully at sacred sites","Plan around heat and walking time","An early start makes a long heritage day more comfortable"]},
 trincomalee:{mood:"Turquoise water, sacred cliffs & slow east-coast days",highlights:["Give Nilaveli or Uppuveli a full unhurried morning","Pair the coast with Fort Frederick and Koneswaram","Leave an evening free for the harbour sunset"],tips:["May to September is the strongest east-coast window","Keep marine plans flexible around sea conditions","Allow extra time for the northbound coastal road"]},
 "arugam-bay":{mood:"Surf, lagoons & easygoing east-coast village life",highlights:["Build the day around the surf conditions","Explore lagoon and wildlife areas away from the main strip","Keep evenings relaxed with local food and a beach walk"],tips:["May to September is the main surf season","Use a local instructor if you are new to the breaks","Do not pack surf, lagoon and safari activities into one rushed day"]},
 jaffna:{mood:"Northern heritage, bold flavours & island-road discovery",highlights:["Spend time around Nallur and the old city","Explore the food culture through a local-led trail","Keep a half-day for a quieter island or coastal drive"],tips:["Dress respectfully at active religious sites","Midday heat can be strong, so pace long walks","Leave room for local food stops rather than fixed meal times"]},
 udawalawe:{mood:"Open grasslands, elephants & quiet wildlife mornings",highlights:["Make an early safari the anchor of the stay","Use the afternoon for a slower village or countryside experience","Keep the route flexible around wildlife and heat"],tips:["Early starts are usually the most comfortable","Wildlife sightings are never guaranteed, so keep expectations flexible","Combine safari time with a rest period rather than another long drive"]},
 "adams-peak":{mood:"Sacred pilgrimage, mountain air & a sunrise worth the climb",highlights:["Climb the pilgrimage route on foot and experience the changing atmosphere as you gain height","Reach the summit around dawn when conditions allow and take in the surrounding mountain landscape","Notice the living pilgrimage traditions and places of worship along the route"],tips:["The main pilgrimage season runs roughly from December to May","Two established approaches include the Hatton side and the Ratnapura side; the climb is on foot","Expect a demanding stair climb, changing weather and colder conditions near the summit; carry water and pace yourself"]}
};
async function getDestination(slug:string){if(!process.env.DATABASE_URL)return null;const sql=neon(process.env.DATABASE_URL);const rows=await sql`SELECT id,slug,name,region,summary,description,latitude,longitude,best_time FROM destinations WHERE slug=${slug} LIMIT 1`;return (rows[0] as Destination|undefined)??null}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const d=await getDestination(slug).catch(()=>null);if(!d)return {title:"Destination not found | DiscoverLanka"};return {title:`${d.name}, Sri Lanka | DiscoverLanka`,description:d.summary,alternates:{canonical:`/destinations/${d.slug}`},openGraph:{title:`${d.name}, Sri Lanka | DiscoverLanka`,description:d.summary,type:"article",images:[{url:images[d.slug]??images.ella,alt:d.name}]}}}
export default async function DestinationPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const d=await getDestination(slug).catch(()=>null);if(!d)notFound();const image=images[d.slug]??images.ella;const g=guide[d.slug]??{mood:"A Sri Lankan place worth exploring at your own pace",highlights:["Take the day slowly and leave room for discovery","Mix a signature sight with a quieter local experience","Use the destination as one part of a wider route"],tips:["Check your route before locking in every stop","Leave buffer time for transport","Build the day around your interests"]};return <main className="destination-detail-page min-h-screen bg-[#0a1712] text-[#f4efe6]">
<header className="absolute inset-x-0 top-0 z-30 px-4 pt-4 sm:px-6"><div className="mx-auto flex max-w-7xl items-center justify-between rounded-full border border-white/12 bg-black/20 px-5 py-4 backdrop-blur-xl"><a href="/" className="text-xl font-semibold">Discover<span className="text-[#d8b875]">Lanka</span></a><a href="/destinations" className="rounded-full border border-white/15 bg-white/5 px-4 py-2 text-xs font-bold uppercase tracking-[.14em] text-white/70">← Destinations</a></div></header>
<section className="relative min-h-[78svh] overflow-hidden"><img src={image} alt={d.name} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(3,10,8,.30),rgba(3,10,8,.15)_35%,rgba(3,10,8,.96)_100%)]"/><div className="relative mx-auto flex min-h-[78svh] max-w-7xl items-end px-5 pb-12 pt-40 sm:px-8 md:pb-16"><div className="route-hero-panel max-w-3xl"><p className="luxury-section-eyebrow">{d.region}</p><h1 className="font-serif mt-3 text-[4.2rem] leading-[.86] tracking-[-.05em] sm:text-7xl md:text-8xl lg:text-[6.4rem]">{d.name}</h1><p className="destination-copy mt-5 max-w-2xl text-base leading-8 text-white/70 md:text-lg">{d.summary}</p><div className="mt-7 flex flex-wrap gap-3"><a href={`/plan?destination=${encodeURIComponent(d.slug)}`} className="premium-button premium-button-gold rounded-full px-6 py-3 text-xs font-extrabold uppercase tracking-[.16em]">Build My Trip ↗</a></div></div></div></section>
<section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[1fr_340px]"><article><p className="luxury-section-eyebrow">About the destination</p><h2 className="mt-3 font-serif text-5xl leading-[.9] tracking-[-.04em] sm:text-6xl lg:text-7xl">A place worth taking your time with.</h2><p className="mt-7 whitespace-pre-line text-base leading-8 text-white/65 md:text-lg">{aboutDescriptions[d.slug]??d.description}</p><div className="mt-12 grid gap-5 md:grid-cols-2"><div className="destination-info-card rounded-[1.6rem] p-7"><p className="luxury-section-eyebrow">The feel</p><h3 className="mt-3 font-serif text-2xl leading-tight">{g.mood}</h3></div><div className="luxury-glass rounded-[1.8rem] p-7"><p className="luxury-section-eyebrow">Best time</p><h3 className="mt-3 font-serif text-2xl">{d.best_time}</h3></div></div></article><aside className="destination-plan-card h-fit rounded-[1.8rem]"><p className="luxury-section-eyebrow">Plan your visit</p><div className="mt-6 space-y-5"><div><span className="text-[10px] uppercase tracking-[.18em] text-white/45">Region</span><strong className="mt-1 block">{d.region}</strong></div><div><span className="text-[10px] uppercase tracking-[.18em] text-white/45">Coordinates</span><strong className="mt-1 block">{d.latitude.toFixed(4)}, {d.longitude.toFixed(4)}</strong></div></div><a href={`/plan?destination=${encodeURIComponent(d.slug)}`} className="premium-button premium-button-gold mt-8 block rounded-full px-5 py-3 text-center text-xs font-extrabold uppercase tracking-[.16em]">Plan around {d.name} ↗</a></aside></section>
<section className="mx-auto max-w-7xl px-5 pb-12 sm:px-8"><p className="luxury-section-eyebrow">Real photos</p><h2 className="mt-2 font-serif text-4xl text-white sm:text-5xl">See Sri Pada before you go.</h2><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{galleries[d.slug]?.map((photo,i)=><a key={photo.src} href={photo.src} target="_blank" rel="noreferrer" className="group relative overflow-hidden rounded-[1.4rem] border border-white/10"><img src={photo.src} alt={photo.alt} loading={i<3?"eager":"lazy"} className="h-[250px] w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 to-transparent p-5 pt-12"><p className="destination-photo-caption text-sm text-white/85">{photo.caption}</p><span className="mt-1 block text-[9px] font-bold uppercase tracking-[.16em] text-white/45">View source photo ↗</span></div></a>)}</div><p className="mt-4 text-[10px] uppercase tracking-[.14em] text-white/35">Photo sources: Wikimedia Commons. Open each image to see its author and license.</p></section><section className="mx-auto max-w-7xl px-5 pb-20 sm:px-8"><div className="grid gap-8 md:grid-cols-2"><div className="destination-content-card rounded-[1.8rem] p-7 sm:p-9"><p className="luxury-section-eyebrow">Things to do</p><div className="mt-5 space-y-3">{g.highlights.map((x)=><div key={x} className="rounded-2xl border border-white/8 bg-white/[.035] p-4 text-sm leading-6 text-white/65">{x}</div>)}</div></div><div className="planning-notes-card luxury-glass rounded-[2rem] p-7 sm:p-9"><p className="luxury-section-eyebrow">Planning notes</p><div className="mt-5 space-y-3">{g.tips.map((x)=><div key={x} className="rounded-2xl border border-white/8 bg-white/[.035] p-4 text-sm leading-6 text-white/65">{x}</div>)}</div></div></div></section>
<div className="mx-auto max-w-7xl px-5 pb-24 sm:px-8"><ReviewSection destinationId={d.id} destinationName={d.name}/></div>
<style>{`.destination-detail-page{background:radial-gradient(circle at 12% 12%,rgba(216,184,117,.08),transparent 25%),radial-gradient(circle at 88% 32%,rgba(46,104,80,.13),transparent 30%),#0a1712}.destination-detail-page .destination-info-card,.destination-detail-page .destination-content-card,.destination-detail-page .destination-plan-card{border:1px solid rgba(255,255,255,.09);background:linear-gradient(145deg,rgba(255,255,255,.075),rgba(255,255,255,.028));box-shadow:0 24px 70px rgba(0,0,0,.22),inset 0 1px 0 rgba(255,255,255,.045);backdrop-filter:blur(20px) saturate(115%);-webkit-backdrop-filter:blur(20px)}.destination-detail-page .destination-info-card,.destination-detail-page .destination-content-card{transition:transform .3s ease,border-color .3s ease,box-shadow .3s ease}.destination-detail-page .destination-info-card:hover,.destination-detail-page .destination-content-card:hover{transform:translateY(-3px);border-color:rgba(216,184,117,.22);box-shadow:0 30px 82px rgba(0,0,0,.28)}.destination-detail-page .destination-content-card>div>div{transition:background .25s ease,border-color .25s ease,transform .25s ease}.destination-detail-page .destination-content-card>div>div:hover{background:rgba(216,184,117,.065);border-color:rgba(216,184,117,.18);transform:translateX(3px)}.destination-detail-page .luxury-section-eyebrow{color:#d8b875;font-size:.58rem;font-weight:800;letter-spacing:.26em;text-transform:uppercase}.destination-detail-page .destination-copy,.destination-detail-page article p.whitespace-pre-line,.destination-detail-page .destination-content-card>div>div,.destination-detail-page .destination-photo-caption,.destination-detail-page .planning-notes-card,.destination-detail-page .planning-notes-card *{font-family:"Cormorant","Cormorant Garamond",Georgia,serif !important}.destination-detail-page .destination-plan-card span,.destination-detail-page .destination-plan-card strong{font-family:"Cormorant","Cormorant Garamond",Georgia,serif}.destination-detail-page article p.whitespace-pre-line{color:rgba(244,239,230,.66);font-size:1.12rem;line-height:1.78;letter-spacing:.005em}.destination-detail-page h1,.destination-detail-page h2,.destination-detail-page h3,.destination-detail-page h4{font-family:"amoera","Amoera",sans-serif !important;font-weight:700;letter-spacing:-.018em}.destination-detail-page section{scroll-margin-top:100px}@media(max-width:640px){.destination-detail-page article p.whitespace-pre-line{font-size:1.03rem;line-height:1.7}.destination-detail-page h1{font-size:3.65rem;line-height:.9}.destination-detail-page h2{font-size:3rem}}`}</style></main>}
