"use client";

import { useEffect, useMemo, useState } from "react";

type Destination = { id:string; slug:string; name:string; region:string; summary:string; latitude:number; longitude:number; best_time?:string|null };
type Event = { id:string; name:string; description:string|null; location:string|null; starts_at:string|null; ends_at:string|null; official_source:string|null };
type Season = { id:string; name:string; starts_month:number; ends_month:number; notes:string|null };

const interests = ["Mountains","Coast","Wildlife","Culture","Food","Slow travel"];
const budgets = ["Budget","Comfort","Premium"];
const daysOptions = [3,5,7,10,14];
const profiles:Record<string,string[]> = {
  Mountains:["ella","nuwara-eliya","kandy","sigiriya"], Coast:["galle","mirissa","kandy","ella"],
  Wildlife:["yala","ella","kandy","mirissa"], Culture:["sigiriya","kandy","anuradhapura","galle"],
  Food:["kandy","galle","mirissa","ella"], "Slow travel":["ella","nuwara-eliya","galle","mirissa"]
};
const rates:Record<string,number> = { Budget:9000, Comfort:18000, Premium:35000 };

function addDays(v:string,n:number){const d=new Date(`${v}T12:00:00`);d.setDate(d.getDate()+n);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function km(a:Destination,b:Destination){const r=Math.PI/180,dl=(b.latitude-a.latitude)*r,do_= (b.longitude-a.longitude)*r,la=a.latitude*r,lb=b.latitude*r;const x=Math.sin(dl/2)**2+Math.sin(do_/2)**2*Math.cos(la)*Math.cos(lb);return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function dateHit(e:Event,start:string,end:string){const a=e.starts_at?new Date(e.starts_at).toISOString().slice(0,10):null;const b=e.ends_at?new Date(e.ends_at).toISOString().slice(0,10):(a);return Boolean(a&&a<=end&&(b??a)>=start)}

export default function Level5PlannerPage(){
 const [destinations,setDestinations]=useState<Destination[]>([]),[events,setEvents]=useState<Event[]>([]),[seasons,setSeasons]=useState<Season[]>([]);
 const [days,setDays]=useState(7),[travelers,setTravelers]=useState(2),[interest,setInterest]=useState("Mountains"),[budget,setBudget]=useState("Comfort"),[startDate,setStartDate]=useState("");
 const [generated,setGenerated]=useState<{destination:Destination;days:number;role:string;score:number}[]>([]),[message,setMessage]=useState("");
 useEffect(()=>{Promise.all([fetch("/api/destinations",{cache:"no-store"}).then(r=>r.json()),fetch("/api/events",{cache:"no-store"}).then(r=>r.json())]).then(([d,e])=>{setDestinations(Array.isArray(d.destinations)?d.destinations:[]);setEvents(Array.isArray(e.events)?e.events:[]);setSeasons(Array.isArray(e.seasons)?e.seasons:[])}).catch(()=>setMessage("Planning data is temporarily unavailable."));try{const s=JSON.parse(localStorage.getItem("discoverlanka-plan")??"{}");if(daysOptions.includes(s.days))setDays(s.days);if(Number.isInteger(s.travelers))setTravelers(Math.max(1,Math.min(10,s.travelers)));if(interests.includes(s.interest))setInterest(s.interest);if(budgets.includes(s.budget))setBudget(s.budget);if(typeof s.startDate==="string")setStartDate(s.startDate)}catch{}},[]);
 const season=useMemo(()=>{if(!seasons.length)return null;const m=new Date(`${startDate||new Date().toISOString().slice(0,10)}T12:00:00`).getMonth()+1;return seasons.find(s=>s.starts_month<=s.ends_month?m>=s.starts_month&&m<=s.ends_month:m>=s.starts_month||m<=s.ends_month)||seasons[0]},[seasons,startDate]);
 const activeEvents=useMemo(()=>startDate?events.filter(e=>dateHit(e,startDate,addDays(startDate,days-1))):[],[events,startDate,days]);
 const ranked=useMemo(()=>{const list=profiles[interest]??profiles.Mountains;return destinations.map(d=>{let score=30+(list.indexOf(d.slug)>=0?55-list.indexOf(d.slug)*7:0);const notes=season?.notes??"";if(["galle","mirissa"].includes(d.slug)&&/south|west/i.test(notes))score+=8;if(["yala","sigiriya","anuradhapura"].includes(d.slug)&&/east|north/i.test(notes))score+=8;if(activeEvents.some(e=>(e.location??"").toLowerCase().includes(d.name.toLowerCase())))score+=10;return {d,score}}).sort((a,b)=>b.score-a.score)},[destinations,interest,season,activeEvents]);
 const plan=useMemo(()=>{const max=days>=10?4:days>=7?3:2;const chosen=ranked.slice(0,max).map(x=>x.d);const out:any[]=[];chosen.forEach((d,i)=>{const previous=out[out.length-1];const dist=previous?km(previous.destination,d):0;if(previous&&dist>300&&out.length<2)return;out.push({destination:d,days:Math.max(1,Math.floor(days/chosen.length)+(i<days%chosen.length?1:0)),role:i===0?"Arrival / anchor":i===chosen.length-1?"Final base":"Middle base",score:ranked.find(x=>x.d.slug===d.slug)?.score??0})});return out},[ranked,days]);
 const metrics=useMemo(()=>{const routeKm=plan.slice(1).reduce((t,x,i)=>t+km(plan[i].destination,x.destination),0);const transit=plan.reduce((t,x)=>t+Math.min(2,Math.max(0,x.days-1)),0);const pace=days/Math.max(1,plan.length);const restDays=plan.filter(x=>x.days>=4).length;const eventDays=Math.min(days,activeEvents.length);const quality=Math.max(70,Math.min(98,Math.round(92-routeKm/700-transit*2+eventDays*2+(pace>=2?3:0))));return{routeKm,transit,restDays,eventDays,quality,paceLabel:pace>=3?"relaxed":pace>=2?"balanced":"busy"}},[plan,days,activeEvents]);
 const estimate=useMemo(()=>{const base=(rates[budget]??rates.Comfort)*days*travelers;const move=1+Math.max(0,plan.length-1)*0.16;const accommodation=base*.42,food=base*.23,transport=base*.18*move,activities=base*.17*move;return accommodation+food+transport+activities},[budget,days,travelers,plan.length]);
 const generate=async()=>{if(!plan.length)return;setGenerated(plan);setMessage("");const payload={title:`Quality-first Sri Lanka ${days}-day ${interest} journey`,days,travelers,interest,budgetLevel:budget,budgetEstimate:estimate,startDate:startDate||null,endDate:startDate?addDays(startDate,days-1):null,selectedSlugs:plan.map(x=>x.destination.slug),itinerary:plan.map((x,i)=>({day:i+1,destination:x.destination.name,allocatedDays:x.days,role:x.role,score:x.score})),events:activeEvents};localStorage.setItem("discoverlanka-plan-level5",JSON.stringify({days,travelers,interest,budget,startDate,plan:generated}));try{const r=await fetch("/api/trips",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error();const t=await r.json();localStorage.setItem("discoverlanka-trip-id",String(t.trip.id));if(t.trip.share_token)localStorage.setItem("discoverlanka-share-token",String(t.trip.share_token));const i=await fetch("/api/itineraries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tripId:String(t.trip.id),title:`${days}-day quality-first itinerary`,summary:`${metrics.quality}% quality · ${metrics.paceLabel} pace · ${Math.round(metrics.routeKm)} km routing.`,durationDays:days,budgetLevel:budget,content:{plan,quality:metrics,season:season?.name??null,events:activeEvents}})});if(!i.ok)throw new Error();setMessage("Level 5 quality-first trip saved.")}catch{setMessage("Quality-first trip is ready in this browser. Server sync is unavailable right now.")}};
 return <main className="min-h-screen px-5 py-28 text-[#f4efe6] sm:px-8"><div className="mx-auto max-w-7xl">
  <div className="border-b border-white/10 pb-10"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#d8b875]">TRIP PLANNER · INTELLIGENCE LEVEL 5</p><h1 className="mt-4 text-5xl font-semibold md:text-7xl">A better trip, measured for real life.</h1><p className="mt-5 max-w-3xl text-white/60">The quality engine balances route distance, base changes, pace, rest room, season signals and events before it saves the trip.</p></div>
  <section className="mt-10 grid gap-4 lg:grid-cols-5">{[["Trip length",<select value={days} onChange={e=>setDays(Number(e.target.value))} className="mt-2 w-full rounded-2xl border border-white/10 bg-white/[.06] px-4 py-3">{daysOptions.map(v=><option key={v}>{v} days</option>)}</select>],["Travelers",<input type="number" min={1} max={10} value={travelers} onChange={e=>setTravelers(Math.max(1,Math.min(10,Number(e.target.value)||1)))} className="mt-2 w-full rounded-2xl border border-white/10 bg-white/[.06] px-4 py-3"/>],["Main feeling",<select value={interest} onChange={e=>setInterest(e.target.value)} className="mt-2 w-full rounded-2xl border border-white/10 bg-white/[.06] px-4 py-3">{interests.map(v=><option key={v}>{v}</option>)}</select>],["Budget",<select value={budget} onChange={e=>setBudget(e.target.value)} className="mt-2 w-full rounded-2xl border border-white/10 bg-white/[.06] px-4 py-3">{budgets.map(v=><option key={v}>{v}</option>)}</select>],["Start date",<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} className="mt-2 w-full rounded-2xl border border-white/10 bg-white/[.06] px-4 py-3"/>]].map(([label,field])=><label key={String(label)} className="rounded-[1.5rem] border border-white/10 bg-white/[.035] p-5 text-sm font-semibold">{label}{field}</label>)}</section>
  <section className="mt-8 grid gap-4 md:grid-cols-4"><div className="premium-card p-6"><p className="text-xs uppercase tracking-widest text-white/45">Quality score</p><p className="mt-2 text-4xl font-semibold">{metrics.quality}%</p></div><div className="premium-card p-6"><p className="text-xs uppercase tracking-widest text-white/45">Route distance</p><p className="mt-2 text-4xl font-semibold">{Math.round(metrics.routeKm)} km</p></div><div className="premium-card p-6"><p className="text-xs uppercase tracking-widest text-white/45">Pace</p><p className="mt-2 text-4xl font-semibold capitalize">{metrics.paceLabel}</p></div><div className="premium-card p-6"><p className="text-xs uppercase tracking-widest text-white/45">Estimated total</p><p className="mt-2 text-2xl font-semibold">LKR {Math.round(estimate).toLocaleString("en-LK")}</p></div></section>
  <section className="mt-10 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="premium-card p-7"><div className="flex items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-[#d8b875]">Recommended flow</p><h2 className="mt-2 text-3xl">{plan.length} bases · {days} days</h2></div><button onClick={generate} disabled={!plan.length||busy} className="premium-button premium-button-gold">{busy?"Building…":"Build Level 5 trip ↗"}</button></div><div className="mt-6 grid gap-3">{plan.map((x:any,i:number)=><div key={x.destination.slug} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-white/40">Stop {i+1} · {x.role}</p><h3 className="mt-1 text-2xl">{x.destination.name}</h3><p className="mt-2 text-sm text-white/55">{x.destination.region} · {x.days} planned day{x.days===1?"":"s"}</p></div><span className="rounded-full border border-white/10 px-3 py-1 text-xs">Score {x.score}</span></div></div>)}</div></div>
   <aside className="premium-card p-7"><p className="text-xs uppercase tracking-widest text-[#d8b875]">Why this route works</p><div className="mt-5 space-y-4 text-sm text-white/65"><p><strong className="text-white">Distance aware:</strong> avoids stacking unnecessarily long hops.</p><p><strong className="text-white">Pace checked:</strong> keeps the number of bases sensible for your trip length.</p><p><strong className="text-white">Season aware:</strong> uses the selected date to nudge the route.</p><p><strong className="text-white">Event aware:</strong> keeps overlapping local events in the quality calculation.</p><p><strong className="text-white">Budget aware:</strong> estimates the trip as accommodation, food, transport and activities.</p></div>{season&&<div className="mt-6 rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-xs uppercase tracking-widest text-white/40">Season signal</p><p className="mt-1 font-semibold">{season.name}</p></div>}{activeEvents.length>0&&<div className="mt-3 rounded-2xl border border-[#d8b875]/20 bg-[#d8b875]/[.06] p-4"><p className="text-xs uppercase tracking-widest text-[#d8b875]">Events in window</p><p className="mt-1">{activeEvents.length} matching event{activeEvents.length===1?"":"s"}</p></div>}</aside></section>
  {generated.length>0&&<div className="mt-6 rounded-2xl border border-[#d8b875]/20 bg-[#d8b875]/[.06] p-5 text-sm">{message||"Quality-first route generated."}</div>}
  <a href="/plan" className="mt-8 inline-flex rounded-full border border-white/15 bg-white/[.05] px-5 py-3 text-sm font-semibold">Back to classic planner ↗</a>
 </div></main>}
