"use client";

import { useEffect, useState } from "react";

type Destination = { id: string; name: string; region: string; summary: string; description: string; latitude: number; longitude: number; best_time: string; slug: string };
type Story = { id: string; slug: string; title: string; excerpt: string; category: string };
type Experience = { id: string; slug: string; name: string; category: string | null; summary: string | null };
const destinationImages: Record<string, string> = { kandy:"https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80", ella:"https://images.unsplash.com/photo-1586613837427-44f7a0b1e5e6?auto=format&fit=crop&w=1200&q=80", galle:"https://images.unsplash.com/photo-1566296314736-6eaac1ca0cb9?auto=format&fit=crop&w=1200&q=80", sigiriya:"https://images.unsplash.com/photo-1588598198321-9735fd5246b8?auto=format&fit=crop&w=1200&q=80", yala:"https://images.unsplash.com/photo-1557008075-7f2c5efa4cfd?auto=format&fit=crop&w=1200&q=80", mirissa:"https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?auto=format&fit=crop&w=1200&q=80", "nuwara-eliya":"https://images.unsplash.com/photo-1590123221594-8c5d2c5f3f44?auto=format&fit=crop&w=1200&q=80", anuradhapura:"https://images.unsplash.com/photo-1588258524675-c7f1e3e8d5d8?auto=format&fit=crop&w=1200&q=80" };
const experienceImages: Record<string,string> = { wildlife:"https://images.unsplash.com/photo-1557008075-7f2c5efa4cfd?auto=format&fit=crop&w=1200&q=80", food:"https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=1200&q=80", culture:"https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80", slow:"https://images.unsplash.com/photo-1586613837427-44f7a0b1e5e6?auto=format&fit=crop&w=1200&q=80" };

export default function Home() {
 const [destinations,setDestinations]=useState<Destination[]>([]); const [experiences,setExperiences]=useState<Experience[]>([]); const [stories,setStories]=useState<Story[]>([]); const [saved,setSaved]=useState<string[]>([]);
 useEffect(()=>{ Promise.all([fetch("/api/destinations").then(r=>r.json()),fetch("/api/experiences").then(r=>r.json()),fetch("/api/stories").then(r=>r.json())]).then(([d,e,s])=>{setDestinations(d.destinations??[]);setExperiences(e.experiences??[]);setStories(s.stories??[])}).catch(()=>{}); try{setSaved(JSON.parse(localStorage.getItem("discoverlanka-saved")??"[]"))}catch{} },[]);
 function toggleSaved(slug:string){setSaved(current=>{const next=current.includes(slug)?current.filter(x=>x!==slug):[...current,slug];localStorage.setItem("discoverlanka-saved",JSON.stringify(next));return next})}
 return <main><header className="fixed top-0 z-50 w-full border-b border-white/20 bg-[#10251f]/90 text-white backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><a href="#top" className="text-xl font-bold">Discover<span className="text-[#d9a441]">Lanka</span></a><nav className="hidden gap-7 text-sm md:flex"><a href="#discover">Discover</a><a href="/experiences">Experiences</a><a href="/plan">Plan</a><a href="#stories">Stories</a><a href="#map">Map</a><a href="/my-trip">My Trip</a></nav><a href="/plan" className="rounded-full bg-[#d9a441] px-5 py-2.5 text-sm font-bold text-[#10251f]">Build My Trip</a></div></header>
 <section id="top" className="relative flex min-h-[760px] items-end overflow-hidden bg-[#183d32] text-white"><div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1518002054494-3a6f94352e9d?auto=format&fit=crop&w=2200&q=85')] bg-cover bg-center opacity-55"/><div className="absolute inset-0 bg-gradient-to-t from-[#10251f] via-[#10251f]/35 to-transparent"/><div className="relative mx-auto w-full max-w-7xl px-6 pb-24 pt-40"><p className="mb-5 text-sm font-semibold uppercase tracking-[.28em] text-[#e7c36e]">Sri Lanka, your way</p><h1 className="max-w-4xl text-6xl font-semibold leading-[.95] tracking-[-.04em] md:text-8xl">Discover Sri Lanka.<br/><span className="text-[#e7c36e]">Plan Your Journey.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/80">From misty mountains to wild coastlines, find the places, experiences and stories that make your Sri Lanka unforgettable.</p><div className="mt-9 flex flex-wrap gap-3"><a href="/plan" className="rounded-full bg-white px-7 py-3.5 font-bold text-[#10251f]">Start exploring</a><a href="#discover" className="rounded-full border border-white/40 px-7 py-3.5 font-semibold">Browse destinations</a></div></div></section>
 <section id="discover" className="mx-auto max-w-7xl px-6 py-24"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#b27c1d]">Where to next?</p><h2 className="mt-3 text-4xl font-semibold tracking-tight md:text-5xl">Start with a place.</h2></div><p className="max-w-md text-[#66756f]">Save places as you explore, then use them as the starting point for your trip.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{destinations.slice(0,6).map(d=><div key={d.id} className="group relative h-[420px] overflow-hidden rounded-3xl bg-[#183d32] text-white"><a href={`/destinations/${d.slug}`} className="absolute inset-0"><img src={destinationImages[d.slug]??destinationImages.kandy} alt={d.name} className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/15 to-transparent"/></a><button onClick={()=>toggleSaved(d.slug)} className="absolute right-5 top-5 z-10 rounded-full bg-white/90 px-4 py-2 text-sm font-bold text-[#183d32]">{saved.includes(d.slug)?"♥ Saved":"♡ Save"}</button><div className="absolute bottom-0 z-10 w-full p-7"><p className="text-sm text-white/70">{d.region}</p><h3 className="mt-1 text-3xl font-semibold">{d.name}</h3><p className="mt-2 max-w-sm text-sm text-white/70">{d.summary}</p><a href={`/destinations/${d.slug}`} className="mt-4 inline-block text-sm font-bold text-[#e7c36e]">Explore destination →</a></div></div>)}</div></section>
 <section id="experiences" className="bg-[#183d32] px-6 py-24 text-white"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#e7c36e]">More than places</p><h2 className="mt-3 max-w-3xl text-4xl font-semibold md:text-6xl">Travel for the feeling, not just the photo.</h2></div><a href="/experiences" className="hidden text-sm font-bold text-[#e7c36e] md:block">See all experiences →</a></div><div className="mt-12 grid gap-4 md:grid-cols-4">{experiences.map(x=><a href={`/plan?interest=${encodeURIComponent(x.category??"")}`} key={x.id} className="group overflow-hidden rounded-2xl border border-white/15 bg-white/5 transition hover:-translate-y-1"><img src={experienceImages[x.slug]??experienceImages.wildlife} alt={x.name} className="h-44 w-full object-cover transition duration-500 group-hover:scale-105"/><div className="p-6"><p className="text-xs font-bold uppercase tracking-widest text-[#e7c36e]">{x.category??"Experience"}</p><h3 className="mt-2 text-xl font-semibold">{x.name}</h3><p className="mt-2 text-sm leading-6 text-white/60">{x.summary}</p></div></a>)}</div></div></section>
 <section id="map" className="border-y border-black/5 bg-[#f1eee6] px-6 py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#b27c1d]">Explore the island</p><h2 className="mt-3 text-4xl font-semibold md:text-5xl">Find your next stop on the map.</h2></div><a href="https://www.openstreetmap.org/?mlat=7.8731&mlon=80.7718#map=8/7.8731/80.7718" target="_blank" rel="noreferrer" className="font-bold text-[#183d32]">Open full map ↗</a></div><div className="mt-10 overflow-hidden rounded-[2rem] border border-black/10 bg-white"><iframe title="Sri Lanka map" src="https://www.openstreetmap.org/export/embed.html?bbox=79.6%2C5.8%2C82.1%2C9.9&layer=mapnik" className="h-[430px] w-full border-0" loading="lazy"/><div className="grid gap-3 p-5 sm:grid-cols-2 md:grid-cols-4">{destinations.slice(0,8).map(d=><a key={d.id} href={`/destinations/${d.slug}`} className="rounded-xl bg-[#f7f5ef] px-4 py-3 text-sm font-semibold">{d.name}<span className="ml-2 text-[#8d651d]">→</span></a>)}</div></div></div></section>
 <section id="plan" className="px-6 py-24"><div className="mx-auto max-w-5xl rounded-[2rem] bg-[#e9e2d3] p-8 md:p-14"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#8d651d]">Your journey starts here</p><h2 className="mt-4 text-4xl font-semibold md:text-6xl">Where should you go?</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-[#66756f]">Tell us how you want to travel. We’ll help turn your interests, time and budget into a Sri Lankan journey worth remembering.</p><div className="mt-9 grid gap-3 sm:grid-cols-3"><a href="/plan?interest=Mountains" className="rounded-2xl bg-white p-5 font-semibold">🏔️ Mountains<br/><span className="text-sm font-normal text-[#66756f]">Cool air & adventure</span></a><a href="/plan?interest=Coast" className="rounded-2xl bg-white p-5 font-semibold">🌊 Coast<br/><span className="text-sm font-normal text-[#66756f]">Beaches & sunsets</span></a><a href="/plan?interest=Wildlife" className="rounded-2xl bg-white p-5 font-semibold">🌿 Wild<br/><span className="text-sm font-normal text-[#66756f]">Nature & wildlife</span></a></div><a href="/plan" className="mt-5 inline-block rounded-full bg-[#183d32] px-7 py-3.5 font-bold text-white">Build my trip →</a></div></section>
 <section id="stories" className="border-t border-black/5 px-6 py-24"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#b27c1d]">Stories from the island</p><h2 className="mt-3 text-4xl font-semibold md:text-5xl">Go beyond the guidebook.</h2></div><a href="/stories" className="text-sm font-bold text-[#183d32]">See all stories →</a></div><div className="mt-10 grid gap-5 md:grid-cols-3">{stories.slice(0,3).map(s=><article key={s.id} className="rounded-3xl bg-[#f1eee6] p-7"><p className="text-xs font-bold uppercase tracking-widest text-[#8d651d]">{s.category||"Sri Lanka"}</p><h3 className="mt-3 text-2xl font-semibold">{s.title}</h3><p className="mt-3 leading-7 text-[#66756f]">{s.excerpt}</p><a href={`/stories/${s.slug}`} className="mt-6 inline-block text-sm font-bold text-[#183d32]">Read story →</a></article>)}{stories.length===0&&<p className="md:col-span-3 rounded-3xl bg-[#f1eee6] p-8 text-[#66756f]">New Sri Lanka stories are coming soon.</p>}</div></div></section>
 <footer className="bg-[#10251f] px-6 py-12 text-white"><div className="mx-auto flex max-w-7xl flex-col gap-8 md:flex-row md:items-center md:justify-between"><div><div className="text-xl font-bold">Discover<span className="text-[#d9a441]">Lanka</span></div><p className="mt-2 text-sm text-white/50">{saved.length} saved {saved.length===1?"place":"places"} · <a href="/my-trip" className="text-[#e7c36e]">Open My Trip →</a></p></div><div className="text-sm text-white/50">Discover Sri Lanka. Plan Your Journey.</div></div></footer>
 </main>;
}
