"use client";

import { useEffect, useMemo, useState } from "react";

type Destination = { id: string; slug: string; name: string; region: string; summary: string; image: string; latitude: number; longitude: number; best_time?: string | null };
type Season = { id: string; name: string; starts_month: number; ends_month: number; notes: string | null };
type Event = { id: string; name: string; description: string | null; location: string | null; starts_at: string | null; ends_at: string | null; official_source: string | null };
type ItineraryItem = { time: string; title: string; detail: string };
type ItineraryDay = { day: number; date: string; destination: Destination; focus: string; items: ItineraryItem[]; event?: Event };

const interests = ["Mountains", "Coast", "Wildlife", "Culture", "Food", "Slow travel"];
const budgets = ["Budget", "Comfort", "Premium"];
const dayOptions = [3, 5, 7, 10, 14];
const destinationImages: Record<string, string> = {
  kandy: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=88",
  ella: "https://images.unsplash.com/photo-1586613837427-44f7a0b1e5e6?auto=format&fit=crop&w=1200&q=88",
  galle: "https://images.unsplash.com/photo-1566296314736-6eaac1ca0cb9?auto=format&fit=crop&w=1200&q=88",
  sigiriya: "https://images.unsplash.com/photo-1588598198321-9735fd5246b8?auto=format&fit=crop&w=1200&q=88",
  yala: "https://images.unsplash.com/photo-1557008075-7f2c5efa4cfd?auto=format&fit=crop&w=1200&q=88",
  mirissa: "https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?auto=format&fit=crop&w=1200&q=88",
  "nuwara-eliya": "https://images.unsplash.com/photo-1590123221594-8c5d2c5f3f44?auto=format&fit=crop&w=1200&q=88",
  anuradhapura: "https://images.unsplash.com/photo-1588258524675-c7f1e3e8d5d8?auto=format&fit=crop&w=1200&q=88",
};
const profiles: Record<string, { primary: string[]; secondary: string[]; bestFor: string }> = {
  Mountains: { primary: ["ella", "nuwara-eliya", "kandy", "sigiriya"], secondary: ["galle", "yala", "mirissa"], bestFor: "highlands, viewpoints and scenic rail-country days" },
  Coast: { primary: ["galle", "mirissa", "kandy", "ella"], secondary: ["sigiriya", "nuwara-eliya", "yala"], bestFor: "coastal mornings, historic streets and sunset time" },
  Wildlife: { primary: ["yala", "ella", "kandy", "mirissa"], secondary: ["sigiriya", "nuwara-eliya", "galle"], bestFor: "nature, early starts and open landscapes" },
  Culture: { primary: ["sigiriya", "kandy", "anuradhapura", "galle"], secondary: ["ella", "nuwara-eliya", "yala", "mirissa"], bestFor: "heritage, temples, stories and local traditions" },
  Food: { primary: ["kandy", "galle", "mirissa", "ella"], secondary: ["sigiriya", "nuwara-eliya", "anuradhapura", "yala"], bestFor: "markets, local flavours and relaxed meals" },
  "Slow travel": { primary: ["ella", "nuwara-eliya", "galle", "mirissa"], secondary: ["kandy", "sigiriya", "yala", "anuradhapura"], bestFor: "fewer bases, meaningful stops and breathing room" },
};
const activityTemplates: Record<string, ItineraryItem[]> = {
  Mountains: [{ time: "Morning", title: "Start with the hills", detail: "A gentle walk, viewpoint or tea-country morning while the air is cool." }, { time: "Afternoon", title: "Follow the landscape", detail: "Choose one scenic trail, garden or rail-country stop without rushing." }, { time: "Evening", title: "Golden-hour reset", detail: "Sunset, a local dinner and an easy evening close to your base." }],
  Coast: [{ time: "Morning", title: "Sea-air start", detail: "Take a quiet beach walk and leave the first hours unhurried." }, { time: "Afternoon", title: "Coastal discovery", detail: "Mix one historic, food or local stop with plenty of open time." }, { time: "Evening", title: "Stay for sunset", detail: "Keep the evening near the coast for golden light and a memorable meal." }],
  Wildlife: [{ time: "Morning", title: "Nature first", detail: "Use the early hours for wildlife, birding or a guided nature experience." }, { time: "Afternoon", title: "Open landscape", detail: "Keep the pace loose and make space for the surrounding nature." }, { time: "Evening", title: "Rest & reset", detail: "Return early, hydrate and keep the evening intentionally simple." }],
  Culture: [{ time: "Morning", title: "Heritage morning", detail: "Visit a major cultural place while it is cooler and usually calmer." }, { time: "Afternoon", title: "Local stories", detail: "Explore a historic quarter, craft tradition, museum or community stop." }, { time: "Evening", title: "Taste the place", detail: "Try a local dinner and take a relaxed walk through the area." }],
  Food: [{ time: "Morning", title: "Local breakfast", detail: "Start with a Sri Lankan breakfast and an easy neighbourhood walk." }, { time: "Afternoon", title: "Food discovery", detail: "Make time for a market, regional specialty or cooking-focused experience." }, { time: "Evening", title: "Dinner with a story", detail: "Finish with a memorable local meal rather than another packed stop." }],
  "Slow travel": [{ time: "Morning", title: "Unhurried start", detail: "Sleep in, enjoy breakfast and move slowly through the area." }, { time: "Afternoon", title: "One meaningful experience", detail: "Choose one local experience and keep the surrounding hours flexible." }, { time: "Evening", title: "Golden-hour pause", detail: "Watch the light change, eat locally and let the evening breathe." }],
};
const dailyRates: Record<string, number> = { Budget: 9000, Comfort: 18000, Premium: 35000 };
function toDateInput(value: Date) { return new Date(value.getTime() - value.getTimezoneOffset() * 60000).toISOString().slice(0, 10); }
function addDays(value: string, amount: number) { const date = new Date(`${value}T12:00:00`); date.setDate(date.getDate() + amount); return toDateInput(date); }
function overlapDate(value: string | null, start: string, end: string) { if (!value) return false; const day = new Date(value).toISOString().slice(0, 10); return day >= start && day <= end; }
function seasonForMonth(month: number, seasons: Season[]) { return seasons.find((s) => s.starts_month <= s.ends_month ? month >= s.starts_month && month <= s.ends_month : month >= s.starts_month || month <= s.ends_month) ?? seasons[0]; }

export default function PlanPage() {
  const [destinations, setDestinations] = useState<Destination[]>([]); const [seasons, setSeasons] = useState<Season[]>([]); const [events, setEvents] = useState<Event[]>([]); const [loading, setLoading] = useState(true);
  const [step, setStep] = useState(1); const [days, setDays] = useState(7); const [travelers, setTravelers] = useState(2); const [interest, setInterest] = useState("Mountains"); const [budget, setBudget] = useState("Comfort"); const [startDate, setStartDate] = useState("");
  const [selected, setSelected] = useState<string[]>([]); const [itinerary, setItinerary] = useState<ItineraryDay[]>([]); const [tripId, setTripId] = useState<string | null>(null); const [shareToken, setShareToken] = useState<string | null>(null); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);

  useEffect(() => {
    const params = new URLSearchParams(window.location.search); const interestParam = params.get("interest"); const destinationParam = params.get("destination");
    Promise.all([fetch("/api/destinations", { cache: "no-store" }).then((r) => r.json()), fetch("/api/events", { cache: "no-store" }).then((r) => r.json())]).then(([destinationData, eventData]) => {
      const mapped = (Array.isArray(destinationData.destinations) ? destinationData.destinations : []).map((d: Omit<Destination, "image">) => ({ ...d, image: destinationImages[d.slug] ?? destinationImages.kandy })); setDestinations(mapped); if (Array.isArray(eventData.seasons)) setSeasons(eventData.seasons); if (Array.isArray(eventData.events)) setEvents(eventData.events);
      if (interestParam) { const match = interests.find((x) => x.toLowerCase() === interestParam.toLowerCase()); if (match) setInterest(match); } if (destinationParam) { const found = mapped.find((d: Destination) => d.slug.toLowerCase() === destinationParam.toLowerCase()); if (found) setSelected([found.slug]); }
    }).catch(() => setMessage("Some planning data could not be loaded. Fallback recommendations are still available.")).finally(() => setLoading(false));
    try {
      const saved = JSON.parse(localStorage.getItem("discoverlanka-plan") ?? "{}"); if (dayOptions.includes(saved.days)) setDays(saved.days); if (Number.isInteger(saved.travelers)) setTravelers(Math.max(1, Math.min(10, saved.travelers))); if (interests.includes(saved.interest)) setInterest(saved.interest); if (budgets.includes(saved.budget)) setBudget(saved.budget); if (typeof saved.startDate === "string") setStartDate(saved.startDate);
      const savedSelected = JSON.parse(localStorage.getItem("discoverlanka-saved") ?? "[]"); if (Array.isArray(savedSelected)) setSelected(savedSelected.filter((x): x is string => typeof x === "string")); const localItinerary = JSON.parse(localStorage.getItem("discoverlanka-itinerary") ?? "[]"); if (Array.isArray(localItinerary) && localItinerary.length) { setItinerary(localItinerary); setStep(4); } setTripId(localStorage.getItem("discoverlanka-trip-id")); setShareToken(localStorage.getItem("discoverlanka-share-token"));
    } catch {}
  }, []);
  useEffect(() => { localStorage.setItem("discoverlanka-plan", JSON.stringify({ days, travelers, interest, budget, startDate })); }, [days, travelers, interest, budget, startDate]);

  const season = useMemo(() => seasons.length ? seasonForMonth(new Date(`${startDate || toDateInput(new Date())}T12:00:00`).getMonth() + 1, seasons) : null, [seasons, startDate]);
  const activeEvents = useMemo(() => startDate ? events.filter((event) => { const end = addDays(startDate, days - 1); return overlapDate(event.starts_at, startDate, end) || overlapDate(event.ends_at, startDate, end); }) : [], [events, startDate, days]);
  const recommendations = useMemo(() => { const profile = profiles[interest] ?? profiles.Mountains; return [...profile.primary, ...profile.secondary].map((slug, index) => ({ destination: destinations.find((d) => d.slug === slug), score: 100 - index * 8 })).filter((x): x is { destination: Destination; score: number } => Boolean(x.destination)).map((x) => ({ ...x, score: x.score + (["galle", "mirissa"].includes(x.destination.slug) && /south|west/i.test(season?.notes ?? "") ? 8 : 0) + (["yala", "sigiriya", "anuradhapura"].includes(x.destination.slug) && /east|north/i.test(season?.notes ?? "") ? 6 : 0) })).sort((a, b) => b.score - a.score); }, [destinations, interest, season]);
  const chosen = useMemo(() => selected.map((slug) => destinations.find((d) => d.slug === slug)).filter(Boolean) as Destination[], [destinations, selected]);
  const route = useMemo(() => (chosen.length ? chosen : recommendations.slice(0, days >= 10 ? 4 : days >= 7 ? 3 : 2).map((r) => r.destination)).slice(0, days >= 10 ? 4 : days >= 7 ? 3 : 2), [chosen, recommendations, days]);
  const estimate = useMemo(() => { const daily = dailyRates[budget] ?? dailyRates.Comfort; const factor = Math.max(1, route.length * 0.9); const accommodation = daily * 0.42 * days * travelers; const food = daily * 0.23 * days * travelers; const transport = daily * 0.18 * days * travelers * factor; const activities = daily * 0.17 * days * travelers * factor; return { accommodation, food, transport, activities, total: accommodation + food + transport + activities }; }, [budget, days, travelers, route.length]);
  const money = (value: number) => `LKR ${Math.round(value).toLocaleString("en-LK")}`;
  const toggleDestination = (slug: string) => { setSelected((current) => current.includes(slug) ? current.filter((x) => x !== slug) : [...current, slug]); setItinerary([]); };

  const generateTrip = async () => {
    const usable = route.length ? route : recommendations.slice(0, 3).map((r) => r.destination); if (!usable.length) return; const template = activityTemplates[interest] ?? activityTemplates.Mountains; const start = startDate || toDateInput(new Date());
    const plan: ItineraryDay[] = Array.from({ length: days }, (_, index) => { const destination = usable[index % usable.length]; const date = addDays(start, index); const event = activeEvents.find((item) => overlapDate(item.starts_at, date, date)); const items = template.map((item) => ({ ...item })); if (event) items[1] = { time: "Local event", title: event.name, detail: `${event.location ? `${event.location} · ` : ""}${event.description || "Check the official source for current details."}` }; return { day: index + 1, date, destination, focus: interest, items, event }; });
    const slugs = Array.from(new Set(usable.map((d) => d.slug))); setItinerary(plan); setSelected(slugs); localStorage.setItem("discoverlanka-saved", JSON.stringify(slugs)); localStorage.setItem("discoverlanka-itinerary", JSON.stringify(plan)); setStep(4); setSaving(true); setMessage("");
    try { const tripResponse = await fetch("/api/trips", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: `Sri Lanka ${days}-day ${interest} journey`, days, travelers, interest, budgetLevel: budget, budgetEstimate: estimate.total, startDate: startDate || null, endDate: startDate ? addDays(startDate, days - 1) : null, selectedSlugs: slugs, itinerary: plan, events: activeEvents }) }); const tripData = await tripResponse.json(); if (!tripResponse.ok) throw new Error(tripData.error || "Trip save failed"); const newTripId = String(tripData.trip.id); setTripId(newTripId); localStorage.setItem("discoverlanka-trip-id", newTripId); if (tripData.trip.share_token) { setShareToken(String(tripData.trip.share_token)); localStorage.setItem("discoverlanka-share-token", String(tripData.trip.share_token)); } const itineraryResponse = await fetch("/api/itineraries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ tripId: newTripId, title: `${days}-day ${interest} itinerary`, summary: `Smart starter route for ${travelers} ${travelers === 1 ? "traveler" : "travelers"}.`, durationDays: days, budgetLevel: budget, content: { days: plan, startDate, events: activeEvents, season: season?.name ?? null } }) }); if (!itineraryResponse.ok) throw new Error("Itinerary save failed"); setMessage("Smart route saved to your live trip."); } catch { setMessage("Smart route saved in this browser. Server sync is unavailable right now."); } finally { setSaving(false); }
  };
  async function shareTrip() { if (!shareToken) { setMessage("Generate the trip once to create a share link."); return; } const url = `${window.location.origin}/trip/share/${shareToken}`; try { await navigator.clipboard.writeText(url); setMessage("Trip share link copied."); } catch { setMessage(url); } }
  const endDate = startDate ? addDays(startDate, days - 1) : "";

  return <main className="min-h-screen bg-[#07120f] text-[#f4efe6]"><header className="sticky top-0 z-40 px-3 pt-3 sm:px-5"><div className="mx-auto flex max-w-7xl items-center justify-between rounded-full border border-white/10 bg-black/25 px-5 py-4 backdrop-blur-xl"><a href="/" className="text-xl font-semibold">Discover<span className="text-[#d8b875]">Lanka</span></a><nav className="hidden items-center gap-6 text-sm text-white/65 md:flex"><a href="/">Discover</a><a href="/destinations">Destinations</a><a href="/experiences">Experiences</a><a href="/stories">Stories</a><a className="text-white" href="/plan">Plan</a><a href="/my-trip">My Trip</a></nav><a href="/account" className="rounded-full border border-white/10 px-4 py-2 text-xs font-bold text-white/70">Account</a></div></header>
  <section className="mx-auto max-w-7xl px-5 pb-10 pt-24 sm:px-8 md:pt-32"><p className="luxury-section-eyebrow">Trip planner · intelligence level 3</p><h1 className="luxury-display-small mt-4 max-w-5xl text-6xl md:text-8xl">Build a Sri Lanka route that fits how you want to travel.</h1><p className="mt-6 max-w-3xl text-base leading-8 text-white/60 md:text-lg">The planner scores your mood, trip length, selected places and seasonal signals, then turns the strongest matches into a practical day-by-day starter route.</p><div className="mt-8 grid gap-3 sm:grid-cols-4">{["Choose", "Shape", "Curate", "Review"].map((label, index) => <button key={label} type="button" onClick={() => setStep(index + 1)} className={`rounded-2xl border px-4 py-3 text-left ${step === index + 1 ? "border-[#d8b875]/35 bg-[#d8b875]/10" : "border-white/8 bg-white/[.03]"}`}><span className="text-[10px] uppercase tracking-[.2em] text-white/40">0{index + 1}</span><span className="mt-1 block text-sm font-bold">{label}</span></button>)}</div></section>
  <section className="mx-auto max-w-7xl px-5 pb-24 sm:px-8">{loading ? <div className="route-hero-panel p-12 text-center text-white/55">Loading your planner…</div> : <div className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="space-y-6">
    {step === 1 && <section className="route-hero-panel p-7 sm:p-10"><p className="luxury-section-eyebrow">01 · Your travel brief</p><h2 className="mt-3 font-serif text-4xl md:text-5xl">What should Sri Lanka feel like?</h2><div className="mt-7 grid gap-3 sm:grid-cols-2">{interests.map((item) => <button key={item} type="button" onClick={() => setInterest(item)} className={`rounded-2xl border p-5 text-left ${interest === item ? "border-[#d8b875]/45 bg-[#d8b875]/10" : "border-white/10 bg-white/[.03]"}`}><span className="text-lg font-semibold">{item}</span><span className="mt-2 block text-sm leading-6 text-white/50">A route shaped around {profiles[item].bestFor}.</span></button>)}</div><div className="mt-8 flex justify-end"><button onClick={() => setStep(2)} className="premium-button premium-button-gold rounded-full px-6 py-3 text-sm font-extrabold">Continue →</button></div></section>}
    {step === 2 && <section className="route-hero-panel p-7 sm:p-10"><p className="luxury-section-eyebrow">02 · Shape the trip</p><h2 className="mt-3 font-serif text-4xl md:text-5xl">Give the route its boundaries.</h2><div className="mt-7"><p className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-white/40">Days</p><div className="flex flex-wrap gap-2">{dayOptions.map((item) => <button key={item} onClick={() => setDays(item)} className={`rounded-full px-5 py-3 text-sm font-bold ${days === item ? "bg-[#d8b875] text-[#07120f]" : "border border-white/10 bg-white/5 text-white/70"}`}>{item} days</button>)}</div></div><div className="mt-7"><p className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-white/40">Travellers</p><div className="flex items-center gap-3"><button onClick={() => setTravelers(Math.max(1, travelers - 1))} className="h-11 w-11 rounded-full border border-white/10">−</button><span className="min-w-10 text-center text-xl font-semibold">{travelers}</span><button onClick={() => setTravelers(Math.min(10, travelers + 1))} className="h-11 w-11 rounded-full border border-white/10">+</button></div></div><div className="mt-7"><p className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-white/40">Budget level</p><div className="grid gap-3 sm:grid-cols-3">{budgets.map((item) => <button key={item} onClick={() => setBudget(item)} className={`rounded-2xl border p-4 text-left ${budget === item ? "border-[#d8b875]/45 bg-[#d8b875]/10" : "border-white/10 bg-white/[.03]"}`}><span className="font-semibold">{item}</span><span className="mt-1 block text-xs text-white/45">~{money(dailyRates[item])} per traveller / day</span></button>)}</div></div><div className="mt-7 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm"><span className="text-white/45">Start date</span><input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="rounded-2xl border border-white/10 bg-black/20 px-4 py-3.5 text-white" /></label><div className="rounded-2xl border border-white/8 bg-white/[.03] p-4"><span className="text-xs uppercase tracking-[.15em] text-white/35">Route window</span><strong className="mt-2 block">{startDate ? `${startDate} → ${endDate}` : "Flexible dates"}</strong><span className="mt-1 block text-xs text-white/40">Events are added to days when a date is supplied.</span></div></div><div className="mt-8 flex justify-between"><button onClick={() => setStep(1)} className="rounded-full border border-white/10 px-6 py-3 text-sm font-bold text-white/70">← Back</button><button onClick={() => setStep(3)} className="premium-button premium-button-gold rounded-full px-6 py-3 text-sm font-extrabold">Curate route →</button></div></section>}
    {step === 3 && <section className="route-hero-panel p-7 sm:p-10"><p className="luxury-section-eyebrow">03 · Curated route</p><h2 className="mt-3 font-serif text-4xl md:text-5xl">Strongest matches for {interest.toLowerCase()}.</h2>{season && <div className="mt-5 rounded-2xl border border-[#d8b875]/20 bg-[#d8b875]/5 p-4 text-sm text-white/60"><strong className="text-[#ead39f]">Season intelligence · {season.name}</strong><span className="mt-1 block">{season.notes}</span></div>}<div className="mt-7 space-y-3">{recommendations.slice(0, 6).map((item) => <div key={item.destination.id} className={`rounded-2xl border p-4 ${selected.includes(item.destination.slug) ? "border-[#d8b875]/40 bg-[#d8b875]/8" : "border-white/8 bg-white/[.03]"}`}><div className="flex items-center gap-4"><img src={item.destination.image} alt={item.destination.name} className="h-20 w-24 rounded-xl object-cover"/><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><div><span className="text-[10px] uppercase tracking-[.2em] text-white/35">Match {Math.min(99, Math.round(item.score))}%</span><h3 className="mt-1 text-lg font-semibold">{item.destination.name}</h3></div><button onClick={() => toggleDestination(item.destination.slug)} className={`rounded-full px-4 py-2 text-xs font-extrabold ${selected.includes(item.destination.slug) ? "bg-[#d8b875] text-[#07120f]" : "border border-white/10 bg-white/5 text-white/65"}`}>{selected.includes(item.destination.slug) ? "Selected" : "Add"}</button></div><p className="mt-1 line-clamp-2 text-sm leading-6 text-white/45">{item.destination.summary}</p></div></div></div>)}</div><div className="mt-8 flex justify-between"><button onClick={() => setStep(2)} className="rounded-full border border-white/10 px-6 py-3 text-sm font-bold text-white/70">← Back</button><button onClick={generateTrip} disabled={saving || !route.length} className="premium-button premium-button-gold rounded-full px-6 py-3 text-sm font-extrabold disabled:opacity-50">{saving ? "Building…" : "Build smart itinerary ↗"}</button></div></section>}
    {step === 4 && <section id="itinerary" className="route-hero-panel p-7 sm:p-10"><p className="luxury-section-eyebrow">04 · Your smart itinerary</p><h2 className="mt-3 font-serif text-4xl md:text-5xl">A {days}-day {interest.toLowerCase()} journey.</h2><div className="mt-5 flex flex-wrap gap-2 text-xs text-white/45"><span className="rounded-full border border-white/10 bg-white/[.03] px-3 py-1.5">{travelers} {travelers === 1 ? "traveller" : "travellers"}</span><span className="rounded-full border border-white/10 bg-white/[.03] px-3 py-1.5">{budget}</span>{startDate && <span className="rounded-full border border-white/10 bg-white/[.03] px-3 py-1.5">{startDate} → {endDate}</span>}</div><div className="mt-7 space-y-5">{itinerary.map((day) => <article key={day.day} className="rounded-[1.6rem] border border-white/8 bg-white/[.025] p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start"><div className="shrink-0"><span className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#d8b875]">Day {day.day}</span><h3 className="mt-1 text-2xl font-semibold">{day.destination.name}</h3><span className="mt-1 block text-xs text-white/35">{day.date}</span></div><div className="grid flex-1 gap-3">{day.items.map((item) => <div key={`${day.day}-${item.time}`} className="rounded-2xl border border-white/7 bg-black/10 p-4"><div className="text-[10px] font-extrabold uppercase tracking-[.18em] text-white/35">{item.time}</div><h4 className="mt-1 font-semibold">{item.title}</h4><p className="mt-1 text-sm leading-6 text-white/50">{item.detail}</p></div>)}</div></div></article>)}</div><div className="mt-8 grid gap-3 sm:grid-cols-3"><button onClick={shareTrip} className="rounded-full border border-white/10 px-5 py-3 text-sm font-bold text-white/75">Share trip ↗</button><a href={tripId ? "/account" : "/my-trip"} className="rounded-full border border-white/10 px-5 py-3 text-center text-sm font-bold text-white/75">Open saved trip →</a><button onClick={() => setStep(3)} className="premium-button premium-button-gold rounded-full px-5 py-3 text-sm font-extrabold">Adjust route</button></div></section>}
  </div><aside className="space-y-6 lg:sticky lg:top-24 lg:self-start"><section className="luxury-step-card p-6 sm:p-7"><p className="luxury-section-eyebrow">Route snapshot</p><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl border border-white/8 bg-white/[.03] p-4"><span className="text-[10px] uppercase tracking-[.16em] text-white/35">Bases</span><strong className="mt-1 block">{route.length}</strong></div><div className="rounded-2xl border border-white/8 bg-white/[.03] p-4"><span className="text-[10px] uppercase tracking-[.16em] text-white/35">Estimate</span><strong className="mt-1 block">{money(estimate.total)}</strong></div></div><div className="mt-4 rounded-2xl border border-white/8 bg-white/[.03] p-4"><span className="text-[10px] uppercase tracking-[.16em] text-white/35">Intelligence</span><p className="mt-2 text-sm leading-6 text-white/55">Interest + trip length + selected places + seasonal signals shape the recommendation.</p></div></section><section className="route-hero-panel p-6 sm:p-7"><p className="luxury-section-eyebrow">Budget lens</p><div className="mt-5 space-y-3">{[["Stay", estimate.accommodation], ["Food", estimate.food], ["Transport", estimate.transport], ["Experiences", estimate.activities]].map(([label, value]) => <div key={String(label)} className="flex items-center justify-between gap-4 text-sm"><span className="text-white/48">{label}</span><strong>{money(Number(value))}</strong></div>)}</div><div className="mt-5 border-t border-white/8 pt-5"><span className="text-xs text-white/35">Estimated trip total</span><div className="mt-1 text-3xl font-semibold text-[#ead39f]">{money(estimate.total)}</div><p className="mt-2 text-xs leading-5 text-white/35">Planning estimate only.</p></div></section><section className="rounded-[1.6rem] border border-[#d8b875]/15 bg-[#d8b875]/5 p-6"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#d8b875]">Live signals</p><p className="mt-3 text-sm leading-6 text-white/58">{startDate ? `${activeEvents.length} dated event${activeEvents.length === 1 ? "" : "s"} found in your window.` : "Add a start date to make events and seasonal timing part of the recommendations."}</p>{message && <p className="mt-3 rounded-xl border border-white/10 bg-black/10 p-3 text-xs leading-5 text-white/55">{message}</p>}</section></aside></div>}</section></main>;
}
