import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { neon } from "@neondatabase/serverless";
import ReviewSection from "@/components/ReviewSection";

export const dynamic="force-dynamic";
type Experience={id:string;slug:string;name:string;category:string|null;summary:string|null;description:string|null;price_from:number|null;currency:string;destination_name:string|null;destination_slug:string|null};
const images:Record<string,string>={wildlife:"https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=2200&q=88",food:"https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=2200&q=88",culture:"https://images.unsplash.com/photo-1588258524675-c7f1e3e8d5d8?auto=format&fit=crop&w=2200&q=88",slow:"https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=2200&q=88","sigiriya-sunrise":"https://images.unsplash.com/photo-1588598198321-9735fd5246b8?auto=format&fit=crop&w=2200&q=88","tea-country-morning":"https://images.unsplash.com/photo-1590123221594-8c5d2c5f3f44?auto=format&fit=crop&w=2200&q=88","galle-fort-walk":"https://images.unsplash.com/photo-1566296314736-6eaac1ca0cb9?auto=format&fit=crop&w=2200&q=88","kandy-food-evening":"https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=2200&q=88"};
async function getExperience(slug:string){if(!process.env.DATABASE_URL)return null;const sql=neon(process.env.DATABASE_URL);const rows=await sql`SELECT e.id,e.slug,e.name,e.category,e.summary,e.description,e.price_from,e.currency,d.name AS destination_name,d.slug AS destination_slug FROM experiences e LEFT JOIN destinations d ON d.id=e.destination_id WHERE e.slug=${slug} LIMIT 1`;return (rows[0] as Experience|undefined)??null}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const e=await getExperience(slug).catch(()=>null);if(!e)return {title:"Experience not found | DiscoverLanka"};return {title:`${e.name} | DiscoverLanka`,description:e.summary??`Explore ${e.name} in Sri Lanka with DiscoverLanka.`,alternates:{canonical:`/experiences/${e.slug}`},openGraph:{title:`${e.name} | DiscoverLanka`,description:e.summary??"",type:"article",images:[{url:images[e.slug]??images.slow,alt:e.name}]}}}
export default async function ExperiencePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const e=await getExperience(slug).catch(()=>null);if(!e)notFound();const image=images[e.slug]??images.slow;return <main className="min-h-screen bg-[#07120f] text-[#f4efe6]">
<header className="absolute inset-x-0 top-0 z-30 px-4 pt-4 sm:px-6"><div className="mx-auto flex max-w-7xl items-center justify-between rounded-full border border-white/12 bg-black/20 px-5 py-4 backdrop-blur-xl"><a href="/" className="text-xl font-semibold">Discover<span className="text-[#d8b875]">Lanka</span></a><a href="/experiences" className="rounded-full border border-white/15 bg-white/5 px-4 py-2 text-xs font-bold uppercase tracking-[.14em] text-white/70">← Experiences</a></div></header>
<section className="relative min-h-[78svh] overflow-hidden"><img src={image} alt={e.name} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(3,10,8,.28),rgba(3,10,8,.14)_35%,rgba(3,10,8,.97)_100%)]"/><div className="relative mx-auto flex min-h-[78svh] max-w-7xl items-end px-5 pb-12 pt-40 sm:px-8 md:pb-16"><div className="route-hero-panel max-w-3xl"><p className="luxury-section-eyebrow">{e.category??"Experience"} {e.destination_name?`· ${e.destination_name}`:""}</p><h1 className="luxury-display-small mt-3 text-5xl md:text-7xl">{e.name}</h1><p className="mt-5 max-w-2xl text-base leading-8 text-white/70 md:text-lg">{e.summary}</p><div className="mt-7 flex flex-wrap gap-3"><a href={`/plan?interest=${encodeURIComponent(e.category??"")}`} className="premium-button premium-button-gold rounded-full px-6 py-3 text-xs font-extrabold uppercase tracking-[.16em]">Add to My Trip ↗</a>{e.destination_slug&&<a href={`/destinations/${e.destination_slug}`} className="rounded-full border border-white/15 bg-white/5 px-5 py-3 text-xs font-bold uppercase tracking-[.16em] text-white/70">Explore destination</a>}</div></div></div></section>
<section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[1fr_340px]"><article><p className="luxury-section-eyebrow">Experience guide</p><h2 className="mt-3 luxury-display-small text-5xl">Make this part of your Sri Lankan story.</h2><p className="mt-7 whitespace-pre-line text-base leading-8 text-white/65 md:text-lg">{e.description??e.summary??"Explore this experience at your own pace."}</p></article><aside className="route-hero-panel h-fit"><p className="luxury-section-eyebrow">Plan this experience</p><div className="mt-6 space-y-5">{e.destination_name&&<div><span className="text-[10px] uppercase tracking-[.18em] text-white/45">Destination</span><strong className="mt-1 block">{e.destination_name}</strong></div>}{e.price_from!=null&&<div><span className="text-[10px] uppercase tracking-[.18em] text-white/45">Starting from</span><strong className="mt-1 block">{e.currency} {Number(e.price_from).toLocaleString("en-LK")}</strong></div>}<div><span className="text-[10px] uppercase tracking-[.18em] text-white/45">Mood</span><strong className="mt-1 block">{e.category??"Curated local experience"}</strong></div></div><a href={`/plan?interest=${encodeURIComponent(e.category??"")}`} className="premium-button premium-button-gold mt-8 block rounded-full px-5 py-3 text-center text-xs font-extrabold uppercase tracking-[.16em]">Build around this ↗</a></aside></section>
<div className="mx-auto max-w-7xl px-5 pb-24 sm:px-8"><ReviewSection experienceId={e.id} experienceName={e.name}/></div>
</main>}
