import { notFound } from "next/navigation";
import { neon } from "@neondatabase/serverless";

export const dynamic = "force-dynamic";

type Experience={slug:string;name:string;category:string|null;summary:string|null;description:string|null;price_from:number|null;currency:string;destination_name:string|null;destination_slug:string|null};
const images:Record<string,string>={wildlife:"https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=2200&q=85",food:"https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=2200&q=85",culture:"https://images.unsplash.com/photo-1588258524675-c7f1e3e8d5d8?auto=format&fit=crop&w=2200&q=85",slow:"https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=2200&q=85"};
async function getExperience(slug:string){if(!process.env.DATABASE_URL)return null;const sql=neon(process.env.DATABASE_URL);const rows=await sql`SELECT e.slug,e.name,e.category,e.summary,e.description,e.price_from,e.currency,d.name AS destination_name,d.slug AS destination_slug FROM experiences e LEFT JOIN destinations d ON d.id=e.destination_id WHERE e.slug=${slug} LIMIT 1`;return (rows[0] as Experience|undefined)??null}
export default async function ExperiencePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;let experience:Experience|null=null;try{experience=await getExperience(slug)}catch{experience=null}if(!experience)notFound();const image=images[experience.slug]??images.slow;return <main className="min-h-screen bg-[#f7f5ef] text-[#10251f]"><header className="absolute left-0 top-0 z-20 w-full text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><a href="/" className="text-xl font-bold">Discover<span className="text-[#e7c36e]">Lanka</span></a><a href="/experiences" className="rounded-full border border-white/40 px-5 py-2 text-sm font-semibold backdrop-blur-sm">← Experiences</a></div></header><section className="relative flex min-h-[560px] items-end overflow-hidden text-white"><img src={image} alt={experience.name} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#10251f] via-black/30 to-black/10"/><div className="relative mx-auto w-full max-w-7xl px-6 pb-20 pt-40"><p className="text-sm font-bold uppercase tracking-[.25em] text-[#e7c36e]">{experience.category??"Experience"}</p><h1 className="mt-4 max-w-4xl text-5xl font-semibold tracking-[-.04em] md:text-7xl">{experience.name}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/80">{experience.summary}</p></div></section><section className="mx-auto grid max-w-7xl gap-12 px-6 py-20 md:grid-cols-[1fr_320px]"><article><p className="text-sm font-bold uppercase tracking-[.2em] text-[#b27c1d]">Experience guide</p><h2 className="mt-3 text-4xl font-semibold">Make this part of your Sri Lankan story.</h2><p className="mt-7 whitespace-pre-line text-lg leading-8 text-[#66756f]">{experience.description||experience.summary||"Explore this experience at your own pace."}</p></article><aside className="h-fit rounded-3xl bg-[#e9e2d3] p-7"><h3 className="text-xl font-semibold">Plan this experience</h3><div className="mt-7 space-y-6">{experience.destination_name&&<div><p className="text-xs font-bold uppercase tracking-widest text-[#8d651d]">Destination</p><p className="mt-1 font-medium">{experience.destination_name}</p></div>}{experience.price_from!=null&&<div><p className="text-xs font-bold uppercase tracking-widest text-[#8d651d]">From</p><p className="mt-1 font-medium">{experience.currency} {Number(experience.price_from).toLocaleString("en-LK")}</p></div>}</div><a href={`/plan?interest=${encodeURIComponent(experience.category??"")}`} className="mt-8 block rounded-full bg-[#183d32] px-6 py-3 text-center font-bold text-white">Add to my trip →</a>{experience.destination_slug&&<a href={`/destinations/${experience.destination_slug}`} className="mt-3 block text-center text-sm font-bold text-[#8d651d]">Explore {experience.destination_name} →</a>}</aside></section></main>}
