"use client";

import { useEffect, useMemo, useState } from "react";

type Experience={id:string;slug:string;name:string;category:string|null;summary:string|null;description:string|null;destination_name:string|null};
const images:Record<string,string>={
  wildlife:"https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=1600&q=88",
  food:"https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1600&q=88",
  culture:"https://images.unsplash.com/photo-1588258524675-c7f1e3e8d5d8?auto=format&fit=crop&w=1600&q=88",
  slow:"https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1600&q=88",
  "sigiriya-sunrise":"https://images.unsplash.com/photo-1588598198321-9735fd5246b8?auto=format&fit=crop&w=1600&q=88",
  "tea-country-morning":"https://images.unsplash.com/photo-1590123221594-8c5d2c5f3f44?auto=format&fit=crop&w=1600&q=88",
  "galle-fort-walk":"https://images.unsplash.com/photo-1566296314736-6eaac1ca0cb9?auto=format&fit=crop&w=1600&q=88",
  "kandy-food-evening":"https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1600&q=88"
};
const fallback="https://images.unsplash.com/photo-1586613837427-44f7a0b1e5e6?auto=format&fit=crop&w=1600&q=88";
const filters=["All","Wildlife","Culture","Food","Coast","Slow travel","Heritage"];

export default function ExperiencesPage(){
 const [experiences,setExperiences]=useState<Experience[]>([]);const [saved,setSaved]=useState<string[]>([]);const [filter,setFilter]=useState("All");const [loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/experiences").then(r=>r.json()).then(d=>setExperiences(Array.isArray(d.experiences)?d.experiences:[])).catch(()=>setExperiences([])).finally(()=>setLoading(false));try{const s=JSON.parse(localStorage.getItem("discoverlanka-experiences")??"[]");if(Array.isArray(s))setSaved(s)}catch{}},[]);
 const visible=useMemo(()=>filter==="All"?experiences:experiences.filter(x=>(x.category??"").toLowerCase().includes(filter.toLowerCase())||((x.name??"").toLowerCase().includes(filter.toLowerCase()))),[experiences,filter]);
 function save(slug:string){setSaved(current=>{const next=current.includes(slug)?current.filter(x=>x!==slug):[...current,slug];localStorage.setItem("discoverlanka-experiences",JSON.stringify(next));return next})}
 return <main className="min-h-screen bg-[#07120f] text-[#f4efe6]">
  <header className="sticky top-0 z-40 px-3 pt-3 sm:px-5"><div className="mx-auto flex max-w-7xl items-center justify-between rounded-full border border-white/10 bg-black/20 px-5 py-4 backdrop-blur-xl"><a href="/" className="text-xl font-semibold">Discover<span className="text-[#d8b875]">Lanka</span></a><nav className="hidden items-center gap-6 text-sm text-white/70 md:flex"><a href="/">Discover</a><a href="/destinations">Destinations</a><a className="text-white" href="/experiences">Experiences</a><a href="/stories">Stories</a><a href="/plan">Plan</a><a href="/my-trip">My Trip</a></nav><a href="/plan" className="premium-button premium-button-gold rounded-full px-4 py-2 text-xs font-extrabold">Build My Trip ↗</a></div></header>
  <section className="mx-auto max-w-7xl px-5 pb-12 pt-24 sm:px-8 md:pt-32"><p className="luxury-section-eyebrow">Curated experiences</p><h1 className="luxury-display-small mt-5 max-w-5xl text-6xl md:text-8xl">Choose how you want Sri Lanka to feel.</h1><p className="mt-7 max-w-2xl text-base leading-8 text-white/60 md:text-lg">Wild encounters, local flavours, culture, coast and slower ways to travel — chosen to become part of a meaningful route.</p><div className="mt-9 flex gap-2 overflow-x-auto pb-2">{filters.map(x=><button key={x} type="button" onClick={()=>setFilter(x)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-bold uppercase tracking-[.15em] ${filter===x?"border-[#d8b875]/40 bg-[#d8b875] text-[#07120f]":"border-white/12 bg-white/5 text-white/65"}`}>{x}</button>)}</div></section>
  <section className="mx-auto max-w-7xl px-5 pb-24 sm:px-8">{loading?<div className="route-hero-panel p-10 text-center text-white/60">Loading experiences…</div>:visible.length===0?<div className="route-hero-panel p-10 text-center"><h2 className="font-serif text-3xl">Nothing in this mood yet.</h2><p className="mt-3 text-white/60">Try another category or build a route from the main planner.</p></div>:<div className="space-y-5">{visible.map((x,index)=><article key={x.id} className="group relative overflow-hidden rounded-[2rem] border border-white/10 bg-white/[.03] md:grid md:grid-cols-[1.25fr_1fr] md:min-h-[390px]"><div className="relative min-h-[290px] overflow-hidden md:min-h-full"><img src={images[x.slug]??fallback} alt={x.name} className="absolute inset-0 h-full w-full object-cover transition duration-[1200ms] group-hover:scale-105" loading={index>1?"lazy":"eager"}/><div className="absolute inset-0 bg-gradient-to-t from-[#07120f]/65 via-transparent to-transparent"/><span className="absolute left-5 top-5 rounded-full border border-white/14 bg-black/25 px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-[.2em] text-white/80 backdrop-blur">{x.category??"Experience"}</span></div><div className="flex flex-col justify-between p-7 sm:p-9"><div><p className="luxury-section-eyebrow">{x.destination_name?`Start in ${x.destination_name}`:"Sri Lanka"}</p><h2 className="mt-3 font-serif text-4xl leading-none md:text-5xl">{x.name}</h2><p className="mt-5 max-w-xl text-base leading-7 text-white/62">{x.summary??x.description??"A considered way to experience Sri Lanka."}</p></div><div className="mt-8 flex flex-wrap items-center gap-3"><button type="button" onClick={()=>save(x.slug)} className="rounded-full border border-white/12 bg-white/[.05] px-5 py-3 text-xs font-bold uppercase tracking-[.15em] text-white/75">{saved.includes(x.slug)?"♥ Saved":"♡ Save"}</button><a href={`/plan?interest=${encodeURIComponent(x.category??"")}`} className="premium-button premium-button-gold rounded-full px-5 py-3 text-xs font-extrabold uppercase tracking-[.15em]">Plan around this ↗</a><a href={`/experiences/${x.slug}`} className="text-xs font-bold uppercase tracking-[.15em] text-white/55 hover:text-white">Open experience →</a></div></div></article>)}</div>}</section>
 </main>;
}
