"use client";
import { useEffect,useMemo,useState } from "react";

type Place={slug:string;name:string;region:string;summary:string;image?:string};
type Item={time?:string;title?:string;note?:string};
type Day={day:number;destination?:Place;focus?:string;transfer?:{from:string;km:number;minutes:number};items?:Item[]};
type Trip={id:string;title:string;start_date:string|null;end_date:string|null;budget:number|null;currency:string;status:string;share_token?:string|null;data:{days?:number;travelers?:number;interest?:string;budgetLevel?:string;selectedSlugs?:string[];prompt?:string;itinerary?:Day[];events?:{id:string;name:string;location:string|null;starts_at:string|null;ends_at:string|null}[]}};
const images:Record<string,string>={kandy:"https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=88",ella:"https://images.unsplash.com/photo-1586613837427-44f7a0b1e5e6?auto=format&fit=crop&w=1200&q=88",galle:"https://images.unsplash.com/photo-1566296314736-6eaac1ca0cb9?auto=format&fit=crop&w=1200&q=88",sigiriya:"https://images.unsplash.com/photo-1588598198321-9735fd5246b8?auto=format&fit=crop&w=1200&q=88",yala:"https://images.unsplash.com/photo-1557008075-7f2c5efa4cfd?auto=format&fit=crop&w=1200&q=88",mirissa:"https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?auto=format&fit=crop&w=1200&q=88","nuwara-eliya":"https://images.unsplash.com/photo-1590123221594-8c5d2c5f3f44?auto=format&fit=crop&w=1200&q=88",anuradhapura:"https://images.unsplash.com/photo-1588258524675-c7f1e3e8d5d8?auto=format&fit=crop&w=1200&q=88"};
function prettyDate(value:string|null){return value?new Date(`${value}T12:00:00`).toLocaleDateString("en-LK",{dateStyle:"medium"}):"Flexible dates"}
export default function MyTripPage(){
 const [trip,setTrip]=useState<Trip|null>(null),[places,setPlaces]=useState<Place[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[shareMessage,setShareMessage]=useState("");
 useEffect(()=>{(async()=>{try{const q=new URLSearchParams(location.search);const share=q.get("share");const localId=q.get("tripId")||localStorage.getItem("discoverlanka-trip-id");const d=await (await fetch("/api/destinations")).json();setPlaces((d.destinations||[]).map((p:Place)=>({...p,image:images[p.slug]||images.ella})));let r:Response;if(share){r=await fetch(`/api/trips?share=${encodeURIComponent(share)}`)}else if(localId){r=await fetch(`/api/trips?id=${encodeURIComponent(localId)}`)}else{r=await fetch("/api/me/trips")}if(r.ok){const j=await r.json();if(j.trip){setTrip(j.trip);localStorage.setItem("discoverlanka-trip-id",j.trip.id);if(j.trip.share_token)localStorage.setItem("discoverlanka-share-token",j.trip.share_token);if(j.trip.data?.selectedSlugs)localStorage.setItem("discoverlanka-saved",JSON.stringify(j.trip.data.selectedSlugs))}else if(j.trips?.[0]){setTrip(j.trips[0]);localStorage.setItem("discoverlanka-trip-id",j.trips[0].id);if(j.trips[0].share_token)localStorage.setItem("discoverlanka-share-token",j.trips[0].share_token)}} }catch{setError("Your journey could not be loaded right now.")}finally{setLoading(false)}})()},[]);
 const saved=useMemo(()=>Array.isArray(trip?.data?.selectedSlugs)?trip!.data.selectedSlugs:[],[trip]);const selected=saved.map(s=>places.find(p=>p.slug===s)).filter(Boolean) as Place[];const days=trip?.data?.days||trip?.data?.itinerary?.length||7;const travelers=trip?.data?.travelers||2;const budget=trip?.data?.budgetLevel||"Comfort";const estimate=trip?.budget??((budget==="Premium"?35000:budget==="Budget"?9000:18000)*days*travelers);const money=(n:number)=>`LKR ${Math.round(n).toLocaleString("en-LK")}`;
 async function shareTrip(){const token=trip?.share_token;if(!token){setShareMessage("Share link is not available yet.");return}const url=`${location.origin}/my-trip?share=${encodeURIComponent(token)}`;try{await navigator.clipboard.writeText(url);setShareMessage("Share link copied.")}catch{setShareMessage(url)}}
 const events=trip?.data?.events||[];
 return <main className="min-h-screen px-5 pb-24 pt-24 text-[#f4efe6] sm:px-8 md:pt-28"><div className="mx-auto max-w-7xl"><header className="mb-8 flex items-center justify-between"><a href="/" className="text-xl font-semibold">Discover<span className="text-[#d8b875]">Lanka</span></a><div className="flex flex-wrap gap-3"><button onClick={shareTrip} className="rounded-full border border-[#d8b875]/30 bg-[#d8b875]/10 px-4 py-2 text-xs font-bold text-[#d8b875]">Share trip ↗</button><a href="/account" className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-bold">Account</a><a href="/concierge" className="rounded-full bg-[#d8b875] px-4 py-2 text-xs font-bold text-[#09140f]">New journey ↗</a></div></header>{shareMessage&&<p className="mb-5 text-sm text-[#d8b875]">{shareMessage}</p>}{loading?<div className="route-hero-panel p-12 text-center text-white/55">Loading your private dossier…</div>:error?<div className="route-hero-panel p-8 text-white/65">{error}</div>:!trip?<div className="route-hero-panel p-12 text-center"><p className="luxury-section-eyebrow">Private travel dossier</p><h1 className="mt-3 font-serif text-5xl">Your next journey is waiting.</h1><a href="/concierge" className="mt-7 inline-flex rounded-full bg-[#d8b875] px-7 py-3.5 font-bold text-[#09140f]">Ask the concierge ↗</a></div>:<><section className="route-hero-panel p-6 sm:p-10"><p className="luxury-section-eyebrow">{new URLSearchParams(location.search).has("share")?"Shared travel dossier":"Private travel dossier"}</p><div className="mt-3 flex flex-wrap items-end justify-between gap-6"><div><h1 className="luxury-display-small text-5xl md:text-8xl">{trip.title}</h1><p className="mt-4 max-w-2xl text-white/58">{trip.data.prompt||"A journey shaped around your time, taste, pace and budget."}</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-semibold text-white/55"><span className="rounded-full border border-white/10 bg-white/[.03] px-3 py-1.5">{prettyDate(trip.start_date)} → {prettyDate(trip.end_date)}</span><span className="rounded-full border border-white/10 bg-white/[.03] px-3 py-1.5">{trip.data.interest||"Curated"}</span></div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Days",days],["Travellers",travelers],["Style",budget],["Estimate",money(estimate)]].map(([k,v])=><div key={k} className="route-stat"><span>{k}</span><strong className="!text-base">{v}</strong></div>)}</div></div><div className="mt-8 flex flex-wrap gap-3"><a href="/concierge" className="rounded-full bg-[#d8b875] px-6 py-3 text-sm font-bold text-[#09140f]">Refine with AI ↗</a><button onClick={shareTrip} className="rounded-full border border-[#d8b875]/30 bg-[#d8b875]/10 px-6 py-3 text-sm font-semibold text-[#d8b875]">Copy share link</button><a href="/destinations" className="rounded-full border border-white/10 bg-white/[.03] px-6 py-3 text-sm font-semibold">Explore more</a></div></section>
<section className="luxury-step-card mt-6 p-6 sm:p-8"><p className="luxury-section-eyebrow">Golden Trail</p><h2 className="mt-2 font-serif text-4xl">{selected.map(p=>p.name).join(" → ")||"Your route"}</h2><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{selected.map((p,i)=><a key={p.slug} href={`/destinations/${p.slug}`} className="group rounded-2xl border border-white/8 bg-black/12 p-3"><div className="flex items-center gap-3"><img src={p.image} alt={p.name} className="h-16 w-16 rounded-xl object-cover transition duration-700 group-hover:scale-105"/><div><p className="text-[10px] uppercase tracking-[.16em] text-[#d8b875]">Stop {i+1}</p><p className="mt-1 font-semibold">{p.name}</p><p className="text-xs text-white/40">{p.region}</p></div></div></a>)}</div></section>
{events.length>0&&<section className="luxury-step-card mt-6 p-6 sm:p-8"><p className="luxury-section-eyebrow">Events in your window</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{events.map((event)=><article key={event.id} className="rounded-2xl border border-[#d8b875]/15 bg-[#17362b]/45 p-4"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#d8b875]">{event.starts_at?new Date(event.starts_at).toLocaleDateString("en-LK",{dateStyle:"medium"}):"Date TBA"}</p><h3 className="mt-2 font-semibold">{event.name}</h3><p className="mt-1 text-xs text-white/40">{event.location||"Sri Lanka"}</p></article>)}</div></section>}
<section className="luxury-step-card mt-6 p-6 sm:p-8"><div className="flex items-end justify-between"><div><p className="luxury-section-eyebrow">Day by day</p><h2 className="mt-2 font-serif text-4xl">A realistic rhythm.</h2></div><span className="text-xs text-white/40">{days} days</span></div><div className="mt-7 space-y-3">{(trip.data.itinerary||[]).map(day=><article key={day.day} className="rounded-2xl border border-white/8 bg-black/10 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.17em] text-[#d8b875]">Day {day.day} · {day.focus}</p><h3 className="mt-1 font-serif text-2xl">{day.destination?.name}</h3><p className="text-xs text-white/40">{day.destination?.region}</p></div>{day.transfer&&<span className="rounded-full border border-white/8 bg-white/[.03] px-3 py-1 text-[10px] text-white/42">{day.transfer.from} → {day.destination?.name} · ~{day.transfer.minutes}m</span>}</div><div className="mt-4 grid gap-2 md:grid-cols-3">{(day.items||[]).map((item,i)=><div key={i} className="rounded-xl border border-white/7 bg-white/[.025] p-3"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#d8b875]">{item.time||"Plan"}</p><p className="mt-1 text-sm font-semibold text-white/80">{item.title}</p>{item.note&&<p className="mt-1 text-xs leading-5 text-white/40">{item.note}</p>}</div>)}</div></article>)}</div></section></>}</div></main>}
