"use client";

import { useEffect, useMemo, useState } from "react";

type Place={id:string;slug:string;name:string;region:string;summary:string;image:string};
type TripData={days:number;travelers:number;interest:string;budgetLevel:string;selectedSlugs:string[];itinerary:unknown[]};
type Trip={id:string;title:string;budget:number|null;currency:string;status:string;data:TripData};
type Day={day:number;destination?:{name?:string;region?:string};focus?:string;items?:Array<{time?:string;title?:string}>};
type Itinerary={id:string;title:string;summary:string|null;duration_days:number;budget_level:string;content:{days?:Day[]}};

const images:Record<string,string>={
 kandy:"https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=88",
 ella:"https://images.unsplash.com/photo-1586613837427-44f7a0b1e5e6?auto=format&fit=crop&w=1200&q=88",
 galle:"https://images.unsplash.com/photo-1566296314736-6eaac1ca0cb9?auto=format&fit=crop&w=1200&q=88",
 sigiriya:"https://images.unsplash.com/photo-1588598198321-9735fd5246b8?auto=format&fit=crop&w=1200&q=88",
 yala:"https://images.unsplash.com/photo-1557008075-7f2c5efa4cfd?auto=format&fit=crop&w=1200&q=88",
 mirissa:"https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?auto=format&fit=crop&w=1200&q=88",
 "nuwara-eliya":"https://images.unsplash.com/photo-1590123221594-8c5d2c5f3f44?auto=format&fit=crop&w=1200&q=88",
 anuradhapura:"https://images.unsplash.com/photo-1588258524675-c7f1e3e8d5d8?auto=format&fit=crop&w=1200&q=88"
};
const rates:Record<string,number>={Budget:9000,Comfort:18000,Premium:35000};

export default function MyTripPage(){
 const [saved,setSaved]=useState<string[]>([]),[places,setPlaces]=useState<Place[]>([]),[trip,setTrip]=useState<Trip|null>(null),[itinerary,setItinerary]=useState<Itinerary|null>(null),[loading,setLoading]=useState(true),[copied,setCopied]=useState(false),[error,setError]=useState("");
 useEffect(()=>{async function load(){try{const local=JSON.parse(localStorage.getItem("discoverlanka-saved")??"[]");const id=localStorage.getItem("discoverlanka-trip-id");const r=await fetch("/api/destinations");const d=r.ok?await r.json():{destinations:[]};const rows=Array.isArray(d.destinations)?d.destinations:[];setPlaces(rows.map((x:Omit<Place,"image">)=>({...x,image:images[x.slug]??images.ella})));if(id){const [tr,it]=await Promise.all([fetch(`/api/trips?id=${encodeURIComponent(id)}`),fetch(`/api/itineraries?tripId=${encodeURIComponent(id)}`)]);if(tr.ok){const payload=await tr.json();if(payload?.trip){setTrip(payload.trip);const slugs=Array.isArray(payload.trip.data?.selectedSlugs)?payload.trip.data.selectedSlugs:[];setSaved(slugs.length?slugs:(Array.isArray(local)?local:[]))}}if(it.ok){const payload=await it.json();if(payload?.itinerary)setItinerary(payload.itinerary)}}else if(Array.isArray(local))setSaved(local.filter((v):v is string=>typeof v==="string"))}catch{setError("Could not load the live trip right now.")}finally{setLoading(false)}}load()},[]);
 const selected=useMemo(()=>saved.map(slug=>places.find(p=>p.slug===slug)).filter(Boolean) as Place[],[saved,places]);
 const data=trip?.data;const days=data?.days??itinerary?.duration_days??7;const travelers=data?.travelers??2;const budget=data?.budgetLevel??itinerary?.budget_level??"Comfort";const interest=data?.interest??"Sri Lanka";const estimate=trip?.budget??(rates[budget]??rates.Comfort)*days*travelers;const route=selected.map(p=>p.name).join(" → ");const coverage=Math.min(100,Math.round(selected.length/Math.max(1,days)*100));const money=(v:number)=>`LKR ${Math.round(v).toLocaleString("en-LK")}`;
 async function share(){const text=trip?`${trip.title} · ${route||"Sri Lanka"} · ${days} days · ${money(Number(estimate))}`:`My DiscoverLanka trip: ${route}`;try{if(navigator.share)await navigator.share({title:"My DiscoverLanka Trip",text});else{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1800)}}catch{}}
 function removeStop(slug:string){const next=saved.filter(x=>x!==slug);setSaved(next);localStorage.setItem("discoverlanka-saved",JSON.stringify(next))}
 function clearLocal(){setSaved([]);setTrip(null);setItinerary(null);["discoverlanka-saved","discoverlanka-trip-id","discoverlanka-itinerary","discoverlanka-plan"].forEach(k=>localStorage.removeItem(k))}
 return <main className="min-h-screen bg-[#07120f] text-[#f4efe6]">
  <header className="sticky top-0 z-40 px-3 pt-3 sm:px-5"><div className="mx-auto flex max-w-7xl items-center justify-between rounded-full border border-white/10 bg-black/25 px-5 py-4 backdrop-blur-xl"><a href="/" className="text-xl font-semibold">Discover<span className="text-[#d8b875]">Lanka</span></a><div className="flex items-center gap-4"><a href="/plan" className="text-sm font-semibold text-white/65">Plan trip</a><a href="/destinations" className="hidden text-sm font-semibold text-white/65 sm:block">Discover</a></div></div></header>
  {loading?<div className="mx-auto max-w-3xl px-5 py-32 text-center text-white/55">Loading your journey…</div>:<section className="mx-auto max-w-7xl px-5 pb-28 pt-20 sm:px-8 md:pt-28">
   <div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="luxury-section-eyebrow">Private travel dossier</p><h1 className="luxury-display-small mt-4 max-w-5xl text-6xl md:text-8xl">{trip?.title??"Your Sri Lankan journey."}</h1><p className="mt-5 max-w-2xl text-base leading-8 text-white/60 md:text-lg">A calm workspace for the places you kept, the route you built, and the next decision.</p></div><div className="flex flex-wrap gap-3"><button onClick={share} disabled={!selected.length&&!trip} className="rounded-full border border-white/12 bg-white/5 px-5 py-3 text-xs font-bold uppercase tracking-[.15em] text-white/70 disabled:opacity-40">{copied?"Copied ✓":"Share journey"}</button><a href="/plan" className="premium-button premium-button-gold rounded-full px-5 py-3 text-xs font-extrabold uppercase tracking-[.15em]">Refine journey ↗</a></div></div>
   {error&&<div className="route-hero-panel mt-10 p-6 text-white/70">{error}</div>}
   {!selected.length?<div className="route-hero-panel mt-12 p-10 text-center md:p-16"><span className="text-5xl text-[#d8b875]">✦</span><p className="mt-6 luxury-section-eyebrow">Begin anywhere</p><h2 className="mt-3 font-serif text-4xl">Your journey is waiting.</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-white/55">Choose a destination in the Trip Builder and this becomes your private travel dossier.</p><a href="/plan" className="premium-button premium-button-gold mt-7 inline-flex rounded-full px-7 py-3.5 text-xs font-extrabold uppercase tracking-[.16em]">Build My Trip ↗</a></div>:<>
    <section className="luxury-step-card mt-12 p-5 sm:p-7 md:p-9"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="luxury-section-eyebrow">Golden Trail</p><h2 className="mt-2 font-serif text-4xl">{route}</h2><p className="mt-2 text-sm text-white/50">{selected.length} stop{selected.length===1?"":"s"} · {days} days · {travelers} traveller{travelers===1?"":"s"}</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Style",budget],["Interest",interest],["Budget",money(Number(estimate))],["Sync",trip?"Live":"Browser"]].map(([k,v])=><div key={k} className="rounded-2xl border border-white/8 bg-white/4 px-4 py-3"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-white/40">{k}</p><p className="mt-1 truncate text-sm font-semibold text-white/90">{v}</p></div>)}</div></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4" data-golden-route>{selected.map((place,index)=><a key={place.slug} href={`/destinations/${place.slug}`} className="golden-route-node group rounded-2xl border border-white/8 bg-black/12 p-3 pl-10 transition hover:border-[#d8b875]/35"><div className="flex items-center gap-3"><img src={place.image} alt={place.name} className="h-14 w-14 rounded-xl object-cover transition duration-700 group-hover:scale-105"/><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#d8b875]">Stop {index+1}</p><p className="mt-1 truncate font-semibold text-white/90">{place.name}</p><p className="text-xs text-white/45">{place.region}</p></div></div></a>)}</div></section>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[["Duration",`${days} days`],["Travelers",String(travelers)],["Style",budget],["Interest",interest],["Estimated total",money(Number(estimate))]].map(([k,v],i)=><div key={k} className={`luxury-step-card p-5 ${i===4?"!border-[#d8b875]/25 !bg-[#16382f]/55":""}`}><p className="text-[10px] font-bold uppercase tracking-[.17em] text-[#d8b875]">{k}</p><p className="mt-2 text-xl font-semibold">{v}</p></div>)}</div>
    <section className="luxury-step-card mt-6 p-7 sm:p-9"><div className="flex items-end justify-between gap-5"><div><p className="luxury-section-eyebrow">Journey intelligence</p><h2 className="mt-2 font-serif text-4xl">A route with room to breathe.</h2></div><a href="/plan" className="hidden text-xs font-bold uppercase tracking-[.16em] text-white/50 hover:text-white sm:block">Edit in planner ↗</a></div><div className="mt-7 grid gap-4 lg:grid-cols-[1fr_310px]"><div className="rounded-2xl border border-white/8 bg-black/10 p-5"><div className="flex items-center justify-between text-xs font-bold uppercase tracking-[.16em]"><span className="text-white/55">Plan coverage</span><span className="text-[#d8b875]">{coverage}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/7"><div className="h-full rounded-full bg-[#d8b875] transition-all duration-1000" style={{width:`${coverage}%`}}/></div><p className="mt-4 text-sm leading-6 text-white/48">Your saved stops currently cover {coverage}% of the selected journey days. Keep the route spacious rather than filling every hour.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1"><div className="rounded-2xl border border-white/8 bg-white/4 p-4"><p className="text-[10px] uppercase tracking-[.16em] text-white/40">Average / day</p><p className="mt-1 text-lg font-semibold">{money(Number(estimate)/Math.max(1,days))}</p></div><div className="rounded-2xl border border-white/8 bg-white/4 p-4"><p className="text-[10px] uppercase tracking-[.16em] text-white/40">Per traveler / day</p><p className="mt-1 text-lg font-semibold">{money(Number(estimate)/Math.max(1,days*travelers))}</p></div></div></div></section>
    {itinerary?.content?.days?.length?<section className="luxury-step-card mt-6 p-7 sm:p-9"><p className="luxury-section-eyebrow">Live itinerary</p><h2 className="mt-2 font-serif text-4xl">{itinerary.title}</h2><p className="mt-2 text-sm text-white/50">{itinerary.summary}</p><div className="mt-8 space-y-3">{itinerary.content.days.map(day=><article key={day.day} className="luxury-route-row rounded-2xl border border-white/8 bg-black/10 p-5"><div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.17em] text-[#d8b875]">Day {day.day}</p><h3 className="mt-1 font-serif text-2xl">{day.destination?.name??"Sri Lanka"}</h3></div><p className="text-sm text-white/45">{day.destination?.region??"Sri Lanka"} · {day.focus??interest}</p></div><div className="mt-4 grid gap-2 md:grid-cols-3">{day.items?.map((item,i)=><div key={`${item.time??"plan"}-${i}`} className="rounded-xl border border-white/7 bg-white/4 p-3"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#d8b875]">{item.time??"Plan"}</p><p className="mt-1 text-sm font-semibold text-white/78">{item.title??"Explore locally"}</p></div>)}</div></article>)}</div></section>:null}
    <section className="mt-8"><div className="flex items-end justify-between gap-4 border-b border-white/8 pb-4"><div><p className="luxury-section-eyebrow">Saved places</p><h2 className="mt-2 font-serif text-4xl">The places you kept.</h2></div><button onClick={clearLocal} className="text-xs font-bold uppercase tracking-[.16em] text-white/40 hover:text-white">Clear local</button></div><div className="mt-6 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{selected.map((place,index)=><article key={place.slug} className="luxury-feature-shell group overflow-hidden rounded-[1.8rem]"><div className="relative h-56 overflow-hidden"><img src={place.image} alt={place.name} className="h-full w-full object-cover transition duration-[1100ms] group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-[#06100d]/80 to-transparent"/><span className="absolute left-4 top-4 rounded-full border border-white/14 bg-black/20 px-3 py-1 text-[10px] font-bold uppercase tracking-[.17em]">Stop {index+1}</span></div><div className="p-6"><p className="luxury-section-eyebrow">{place.region}</p><h3 className="mt-2 font-serif text-3xl">{place.name}</h3><p className="mt-3 text-sm leading-6 text-white/52">{place.summary}</p><div className="mt-5 flex items-center justify-between"><a href={`/destinations/${place.slug}`} className="text-xs font-bold uppercase tracking-[.15em] text-white/70">Explore ↗</a><button onClick={()=>removeStop(place.slug)} className="text-xs font-bold uppercase tracking-[.15em] text-white/40 hover:text-white">Remove</button></div></div></article>)}</div></section>
    <div className="luxury-mobile-trip-cta"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#d8b875]">Your journey</p><p className="max-w-[44vw] truncate text-sm font-semibold text-white/85">{route}</p></div><a href="/plan" className="premium-button premium-button-gold rounded-full px-4 py-2.5 text-xs font-extrabold">Refine ↗</a></div>
   </>}
  </section>}
 </main>;
}
